<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 11 N Parameters | Preceptor’s Primer for Bayesian Data Science</title>
<meta name="author" content="David Kane">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.2"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.5.3/header-attrs.js"></script><script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.5.3/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.5.3/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.3.9000/tabs.js"></script><script src="libs/bs3compat-0.2.3.9000/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/htmlwidgets-1.5.2/htmlwidgets.js"></script><script src="libs/plotly-binding-4.9.2.1/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.1.0.1/css/crosstalk.css" rel="stylesheet">
<script src="libs/crosstalk-1.1.0.1/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-1.52.2/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-1.52.2/plotly-latest.min.js"></script><script src="libs/rglWebGL-binding-0.103.5/rglWebGL.js"></script><link href="libs/rglwidgetClass-0.103.5/rgl.css" rel="stylesheet">
<script src="libs/rglwidgetClass-0.103.5/rglClass.min.js"></script><script src="libs/CanvasMatrix4-0.103.5/CanvasMatrix.min.js"></script><script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/mark.js@8.11.1/dist/mark.min.js"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Preceptor’s Primer for Bayesian Data Science</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Welcome</a></li>
<li><a class="" href="preamble.html">Preamble</a></li>
<li><a class="" href="shopping-week.html">Shopping Week</a></li>
<li><a class="" href="visualization.html"><span class="header-section-number">1</span> Visualization</a></li>
<li><a class="" href="wrangling.html"><span class="header-section-number">2</span> Wrangling</a></li>
<li><a class="" href="data.html"><span class="header-section-number">3</span> Data</a></li>
<li><a class="" href="rubin-causal-model.html"><span class="header-section-number">4</span> Rubin Causal Model</a></li>
<li><a class="" href="probability.html"><span class="header-section-number">5</span> Probability</a></li>
<li><a class="" href="one-parameter.html"><span class="header-section-number">6</span> One Parameter</a></li>
<li><a class="" href="two-parameters.html"><span class="header-section-number">7</span> Two Parameters</a></li>
<li><a class="" href="three-parameters.html"><span class="header-section-number">8</span> Three Parameters</a></li>
<li><a class="" href="four-parameters.html"><span class="header-section-number">9</span> Four Parameters</a></li>
<li><a class="" href="five-parameters.html"><span class="header-section-number">10</span> Five Parameters</a></li>
<li><a class="active" href="n-parameters.html"><span class="header-section-number">11</span> N Parameters</a></li>
<li><a class="" href="tools.html">Tools</a></li>
<li><a class="" href="functions.html">Functions</a></li>
<li><a class="" href="shiny.html">Shiny</a></li>
<li><a class="" href="maps.html">Maps</a></li>
<li><a class="" href="ipums.html">IPUMS</a></li>
<li><a class="" href="animation.html">Animation</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/PPBDS/primer">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="n-parameters" class="section level1" number="11">
<h1>
<span class="header-section-number">11</span> N Parameters<a class="anchor" aria-label="anchor" href="#n-parameters"><i class="fas fa-link"></i></a>
</h1>
<!-- MF: Need to replace hard coded numbers. -->
<!-- MF: Add a testing is nonsense section. -->
<!-- Intro before Wisdom talks in generalities and asks the key question, but does not discuss data. Phrase the question as coming from a normal person. -->
<!-- Two goals this week: -->
<!-- Wisdom: Begin with the ideal Preceptor Table. Depends on the question. Might be all voters in Massachusetts. Might be just the Republican voters. This determines if we are causal or predictive.  Then look for data and explore that data. What must I assume about the population, to allow me to go forward? If the data is not "close enough" to my ideal Preceptor Table, I give up. Wisdom is about knowing when to quit.

Justice: Actual Preceptor Table. Then, representativeness (rows), validity (columns). Only the main functional form, with no variable names. Discussion of the error term. 

Courage: For each model, write down the math, estimate the model, say something sensible about the regression table. 

Temperance. Answer the question. Be aware of the limits to the accuracy of your answer. Preceptor's Posterior. Testing. All the cool themes. Bring it all together. Make the students say "Ahhh!" -->
<!-- p_00 = fcn_1(primary_00), should be p_00 = primary_00 == "Yes", -->
<!-- Use fit_ instead of model_. Think about other conventions you want enforce. -->
<p><em>This chapter is still a DRAFT.</em></p>
<p>Having created models with one parameter in Chapter <a href="one-parameter.html#one-parameter">6</a>, two parameters in Chapter <a href="two-parameters.html#two-parameters">7</a>, three parameters in Chapter <a href="three-parameters.html#three-parameters">8</a>, four parameters in Chapter <a href="four-parameters.html#four-parameters">9</a> and five parameters in Chapter <a href="five-parameters.html#five-parameters">10</a>, you are now ready to make the jump to <span class="math inline">\(N\)</span> parameters.</p>
<p>In this chapter, we will consider models with many parameters and the complexities that arise therefrom.</p>
<div id="wisdom-8" class="section level2" number="11.1">
<h2>
<span class="header-section-number">11.1</span> Wisdom<a class="anchor" aria-label="anchor" href="#wisdom-8"><i class="fas fa-link"></i></a>
</h2>
<div class="figure">
<span id="fig:unnamed-chunk-633"></span>
<img src="other/images/Wisdom.jpg" alt="Wisdom" width="100%"><p class="caption">
FIGURE 11.1: Wisdom
</p>
</div>
<p>Imagine you are running for Governor and want to do a better job of getting your voters to vote. You recently read about a large-scale experiment showing the effect of sending out a voting reminder that “shames” citizens who do not vote. You are considering sending out a “shaming” voting reminder yourself.</p>
<p>We will be looking at the <code>shaming</code> dataset from the <strong>primer.data</strong> package. This is dataset is from “Social Pressure and Voter Turnout: Evidence from a Large-Scale Field Experiment” by Gerber, Green, and Larimer (2008). <a href="https://github.com/PPBDS/primer.data/blob/master/inst/papers/shaming.pdf">Check out the paper here</a>. You can, and should, familiarize yourself with the data by typing <code><a href="https://rdrr.io/pkg/primer.data/man/shaming.html">?shaming</a></code>. Our question:</p>
<p><em>What is the causal effect, on the likelihood of voting, of different postcards on voters of different levels of political engagement?</em></p>
<div id="eda-of-shaming" class="section level3" number="11.1.1">
<h3>
<span class="header-section-number">11.1.1</span> EDA of <code>shaming</code><a class="anchor" aria-label="anchor" href="#eda-of-shaming"><i class="fas fa-link"></i></a>
</h3>
<p>Let’s now do an EDA, starting off by running <code>glimpse()</code>.</p>
<div class="sourceCode" id="cb759"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">primer.data</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mc-stan.org/rstanarm/">rstanarm</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://github.com/jrnold/ggthemes">ggthemes</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mjskay.github.io/ggdist/">ggdist</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/rstudio/gt">gt</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/sfirke/janitor">janitor</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://github.com/bbolker/broom.mixed">broom.mixed</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/ddsjoberg/gtsummary">gtsummary</a></span><span class="op">)</span>
<span class="fu">glimpse</span><span class="op">(</span><span class="va">shaming</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 344,084
## Columns: 15
## $ cluster       &lt;chr&gt; "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", …
## $ primary_06    &lt;int&gt; 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1…
## $ treatment     &lt;fct&gt; Civic Duty, Civic Duty, Hawthorne, Hawthorne, Hawthorne…
## $ sex           &lt;chr&gt; "Male", "Female", "Male", "Female", "Female", "Male", "…
## $ age           &lt;int&gt; 65, 59, 55, 56, 24, 25, 47, 50, 38, 39, 65, 61, 57, 37,…
## $ primary_00    &lt;chr&gt; "No", "No", "No", "No", "No", "No", "No", "No", "No", "…
## $ general_00    &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "No", "Yes", "Yes", …
## $ primary_02    &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "No", "Yes", "Yes", …
## $ general_02    &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "No", "Yes", "Yes", …
## $ primary_04    &lt;chr&gt; "No", "No", "No", "No", "No", "No", "No", "No", "No", "…
## $ general_04    &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "Yes",…
## $ hh_size       &lt;int&gt; 2, 2, 3, 3, 3, 3, 3, 3, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1…
## $ hh_primary_04 &lt;dbl&gt; 0.095, 0.095, 0.048, 0.048, 0.048, 0.048, 0.048, 0.048,…
## $ hh_general_04 &lt;dbl&gt; 0.86, 0.86, 0.86, 0.86, 0.86, 0.90, 0.90, 0.90, 0.90, 0…
## $ neighbors     &lt;int&gt; 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,…</code></pre>
<p><code>glimpse()</code> gives us a look at the raw data contained within the <code>shaming</code> data set. At the very top of the output, we can see the number of rows and columns, or observations and variables respectively. We see that there are 344,084 observations, with each row corresponding to a unique respondent. This summary provides an idea of some of the variables we will be working with.</p>
<p>Variables of particular interest to us are <code>sex</code>, <code>hh_size</code>, and <code>primary_06</code>. The variable <code>hh_size</code> tells us the size of the respondent’s household, <code>sex</code> tells us the sex of the respondent, and <code>primary_06</code> tells us whether or not the respondent voted in the 2006 Primary election.
There are a few things to note while exploring this data set. You may – or may not – have noticed that the only response to the <code>general_04</code> variable is “Yes.” In their published article, the authors note that “Only registered voters who voted in November 2004 were selected for our sample” (Gerber, Green, Larimer, 2008). After this, the authors found their history then sent out the mailings. Thus, non-registered voters are excluded from our data.</p>
<p>It is also important to identify the dependent variable and its meaning. In this shaming experiment, the dependent variable is <code>primary_06</code>, which is a variable coded either 0 or 1 for whether or not the respondent voted in the 2006 primary election. This is the dependent variable because the authors are trying to measure the <strong>effect</strong> that the treatments have on voting behavior in the 2006 general election.</p>
<!-- HV: Should I include discussion of the left-hand variable (treatment?) here? Or wait until we move into the regressions? -->
<p>We have not yet discussed the most important variable of them all: <code>treatment</code>. The <code>treatment</code> variable is a factor variable with 5 levels, including the control. Since we are curious as to how sending mailings affects voter turnout, the treatment variable will tell us about the impact each type of mailing can make. Let’s start off by taking a broad look at the different treatments.</p>
<!-- HV: Is it okay to say the first sentence of this paragraph? -->
<div class="sourceCode" id="cb761"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">shaming</span> <span class="op">%&gt;%</span>
  <span class="fu">count</span><span class="op">(</span><span class="va">treatment</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   treatment       n
##   &lt;fct&gt;       &lt;int&gt;
## 1 Control    191243
## 2 Civic Duty  38218
## 3 Hawthorne   38204
## 4 Self        38218
## 5 Neighbors   38201</code></pre>
<p>Four types of treatments were used in the experiment, with voters receiving one of the four types of mailing. All of the mailing treatments carried the message, “DO YOUR CIVIC DUTY - VOTE!”</p>
<p>The first treatment, Civic Duty, also read, “Remember your rights and responsibilities as a citizen. Remember to vote.” This message acted as a baseline for the other treatments, since it carried a message very similar to the one displayed on all the mailings.</p>
<p>In the second treatment, Hawthorne, households received a mailing which told the voters that they were being studied and their voting behavior would be examined through public records. This adds a small amount of social pressure to the households receiving this mailing.</p>
<p>In the third treatment, Self, the mailing includes the recent voting record of each member of the household, placing the word “Voted” next to their name if they did in fact vote in the 2004 election or a blank space next to the name if they did not. In this mailing, the households were also told, “we intend to mail an updated chart” with the voting record of the household members after the 2006 primary. By emphasizing the public nature of voting records, this type of mailing exerts more social pressure on voting than the Hawthorne treatment.</p>
<p>The fourth treatment, Neighbors, provides the household members’ voting records, as well as the voting records of those who live nearby. This mailing also told recipients, “we intend to mail an updated chart” of who voted in the 2006 election to the entire neighborhood.</p>
</div>
<div id="population-1" class="section level3" number="11.1.2">
<h3>
<span class="header-section-number">11.1.2</span> Population<a class="anchor" aria-label="anchor" href="#population-1"><i class="fas fa-link"></i></a>
</h3>
<p>One of the most important components of Wisdom is the concept of the “population.” Recall the questions we asked earlier:</p>
<p><em>What will happen if we do send a voting reminder today? Will more voters show up to the polls? Additionally, on the day of the election, a female citizen is randomly selected. What is the probability she will vote?</em></p>
<p>As we have discussed before, the population <em>is not</em> the set of people, or voters, for which we have data. This is the dataset. The population is the larger — potentially much larger — set of individuals about whom we want to make inferences.</p>
<p>There are many different populations, each with its own <span class="math inline">\(\mu\)</span>, in which we might be interested. For instance:</p>
<ul>
<li>The population for registered voters that voted in the 2004 election in the United States. This is the population for our dataset.</li>
<li>The population for registered voters that voted in any election from 1970 to 2040. We are often interested in the future. We want to make predictions about what <em>will</em> happen to voter habits, not what has already happened.</li>
<li>The population for registered <strong>and</strong> non-registered voters in the United States. Though it is helpful to look at registered voters, candidates also want to get non-registered voters to vote for them!</li>
<li>The population for voters — registered or not-registered — around the world. We might expect the habits of Americans to be similar to the habits of people in other countries. We might also believe that this is too broad a group to make inferences about.</li>
<li>Many more!</li>
</ul>
<p>In this case, we are viewing the data from the perspective of someone running for Governor this year that wants to increase voter turnout. We want to increase turnout <strong>now</strong>, not for people voting in 2006! We also may want to increase turnout in those citizens who are not registered to vote, a group that is excluded from our dataset. Is it reasonable to generate conclusions for this group? Most likely, no. However, we have limited data to work with and we have to determine how far we are willing to generalize to other groups.</p>
<p>It is a judgment call, a matter of Wisdom, as to whether or not that data we have is “close enough” to the population we are interested in to justify making a model.</p>
<p>Even though the original question is about “voters” in general, and does not specifically refer to specific states in which we might be interested, we will assume that the data we have for random voters is, uh, representative enough of the population we are interested in. If we did not believe that, then we should stop right now. <em>The major part of Wisdom is deciding what questions you can’t answer because of the data you just don’t have.</em></p>
<!-- DK: Add discussion of what you see here. No need to drop missing values since there aren't any. I think this next discussion can be dropped. -->
<!-- DK: Note that this situation is different from Chapter 8 in that fitted values and predicted values are not the same thing! The fitted value, for a combination of values for treatment and solo, is something 0.30, meaning that 30% of the people in this bucket votes. But the predicted value must be 0 or 1. Either you voted or you didn't. This example is clearly causal and so you need a Rubin Table with 5 potential outcome columns. The key difference in this chapter is that we are using lots of right hand side variables, both continuous and discrete. -->
</div>
</div>
<div id="justice-and-courage-1" class="section level2" number="11.2">
<h2>
<span class="header-section-number">11.2</span> Justice and Courage<a class="anchor" aria-label="anchor" href="#justice-and-courage-1"><i class="fas fa-link"></i></a>
</h2>
<div class="figure" style="text-align: center">
<span id="fig:unnamed-chunk-636"></span>
<img src="other/images/Justice.jpg" alt="Justice" width="60%"><p class="caption">
FIGURE 11.2: Justice
</p>
</div>
<div class="figure" style="text-align: center">
<span id="fig:unnamed-chunk-637"></span>
<img src="other/images/Courage.jpg" alt="Courage" width="60%"><p class="caption">
FIGURE 11.3: Courage
</p>
</div>
<p>Because we will be going through a series of models in this chapter, it is useful to combine the virtues of Justice and Courage.</p>
<div id="set-up" class="section level3" number="11.2.1">
<h3>
<span class="header-section-number">11.2.1</span> Set-up<a class="anchor" aria-label="anchor" href="#set-up"><i class="fas fa-link"></i></a>
</h3>
<p>We start by creating a function named <code>fcn_1()</code> that takes in a vector of “Yes”/“No” responses and returns a binary integer vector where 1 replaces “Yes,” 0 replaces “No,” and anything else becomes <code>NA</code>. The function should alert the user if they are passing in a problematic vector, i.e. one that contains lowercase “yes” and/or “no.” It will also alert the user if there are not at least once observation equal to “Yes.” You may find the <code>case_when()</code> function to be useful. <code>NA</code> can take on different types depending on the classification of the vector. Read more on this at <code>?NA</code>.</p>
<div class="sourceCode" id="cb763"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fcn_1</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">{</span>
  
  <span class="co"># In effort to prevent people from mis-applying this function, we want to </span>
  <span class="co"># force users to confront the precise state of their data. This function will</span>
  <span class="co"># properly encode capitalized "Yes", capitalized "No" as 0, and will code </span>
  <span class="co"># anything else as NA. We check that there are no lowercase "yes" or "no" </span>
  <span class="co"># instances and that the column provided has at least 1 instance of the</span>
  <span class="co"># properly formatted "Yes" so that there are no missed y/n values and to</span>
  <span class="co"># ensure that the function is being usefully applied.</span>
  
  <span class="co"># We can't check for at least 1 "No" due to the fact that the group was</span>
  <span class="co"># selected such that everyone voted in the 04 general election, so checking</span>
  <span class="co"># for at least 1 "Yes" will have to suffice.</span>
  
  <span class="fu"><a href="https://rdrr.io/r/base/stopifnot.html">stopifnot</a></span><span class="op">(</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span> <span class="op">==</span> <span class="st">"yes"</span><span class="op">)</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span>,
            <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span> <span class="op">==</span> <span class="st">"Yes"</span><span class="op">)</span>  <span class="op">&gt;</span> <span class="fl">0</span><span class="op">)</span>,
            <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">x</span> <span class="op">==</span> <span class="st">"no"</span><span class="op">)</span>  <span class="op">==</span> <span class="fl">0</span><span class="op">)</span><span class="op">)</span>
  
  <span class="co"># You can use an orphaned case_when here or you can assign to an object and </span>
  <span class="co"># return. It works both ways.</span>
  
  <span class="fu">case_when</span><span class="op">(</span><span class="va">x</span> <span class="op">==</span> <span class="st">"Yes"</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/integer.html">as.integer</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span>,
            <span class="va">x</span> <span class="op">==</span> <span class="st">"No"</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/integer.html">as.integer</a></span><span class="op">(</span><span class="fl">0</span><span class="op">)</span>,
            <span class="cn">TRUE</span> <span class="op">~</span> <span class="cn">NA_integer_</span><span class="op">)</span><span class="op">}</span></code></pre></div>
<p>Now, we will create an object named <code>object_1</code> that includes a 3-level factor classifying voters by level of civic engagement.</p>
<ul>
<li><p>Using the function we just created, convert all primary and general election variables <em>that are not already 1/0 binary</em> to binary format.</p></li>
<li><p>Create a new column named <code>civ_engage</code> that sums up each person’s voting behavior up to, but not including, the 2006 primary.</p></li>
<li><p>Create a column named <code>voter_class</code> that classifies voters into 3 bins: “Always Vote” for those who voted at least 5 times, “Sometimes Vote” for those who voted between 3 or 4 times, and “Rarely Vote” for those who voted 2 or fewer times. This variable should be classified as a factor.</p></li>
<li><p>Create a column called <code>z_age</code> which is the z-score for <code>age</code>.</p></li>
</ul>
<div class="sourceCode" id="cb764"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">object_1</span> <span class="op">&lt;-</span> <span class="va">shaming</span> <span class="op">%&gt;%</span> 
  
  <span class="co"># Converting the Y/N columns to binaries with the function we made note that</span>
  <span class="co"># primary_06 is already binary and also that we don't need it to predict</span>
  <span class="co"># construct previous voter behavior status variable.</span>
  
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>p_00 <span class="op">=</span> <span class="fu">fcn_1</span><span class="op">(</span><span class="va">primary_00</span><span class="op">)</span>,
         p_02 <span class="op">=</span> <span class="fu">fcn_1</span><span class="op">(</span><span class="va">primary_02</span><span class="op">)</span>,
         p_04 <span class="op">=</span> <span class="fu">fcn_1</span><span class="op">(</span><span class="va">primary_04</span><span class="op">)</span>,
         g_00 <span class="op">=</span> <span class="fu">fcn_1</span><span class="op">(</span><span class="va">general_00</span><span class="op">)</span>,
         g_02 <span class="op">=</span> <span class="fu">fcn_1</span><span class="op">(</span><span class="va">general_02</span><span class="op">)</span>,
         g_04 <span class="op">=</span> <span class="fu">fcn_1</span><span class="op">(</span><span class="va">general_04</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  
  <span class="co"># A sum of the voting action records across the election cycle columns gives</span>
  <span class="co"># us an idea (though not weighted for when across the elections) of the voters</span>
  <span class="co"># general level of civic involvement.</span>
  
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>civ_engage <span class="op">=</span> <span class="va">p_00</span> <span class="op">+</span> <span class="va">p_02</span> <span class="op">+</span> <span class="va">p_04</span> <span class="op">+</span> 
                      <span class="va">g_00</span> <span class="op">+</span> <span class="va">g_02</span> <span class="op">+</span> <span class="va">g_04</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  
  <span class="co"># If you look closely at the data, you will note that g_04 is always Yes, so</span>
  <span class="co"># the lowest possible value of civ_engage is 1. The reason for this is that</span>
  <span class="co"># the sample was created by starting with a list of everyone who voted in the</span>
  <span class="co"># 2004 general election. Note how that fact makes the interpretation of the</span>
  <span class="co"># relevant population somewhat subtle.</span>
  
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>voter_class <span class="op">=</span> <span class="fu">case_when</span><span class="op">(</span><span class="va">civ_engage</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>, <span class="fl">6</span><span class="op">)</span> <span class="op">~</span> <span class="st">"Always Vote"</span>,
                                 <span class="va">civ_engage</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span> <span class="op">~</span> <span class="st">"Sometimes Vote"</span>,
                                 <span class="va">civ_engage</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span> <span class="op">~</span> <span class="st">"Rarely Vote"</span><span class="op">)</span>,
         voter_class <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">voter_class</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Rarely Vote"</span>, 
                                                      <span class="st">"Sometimes Vote"</span>, 
                                                      <span class="st">"Always Vote"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  
  <span class="co"># Centering and scaling the age variable. Note that it would be smart to have</span>
  <span class="co"># some stopifnot() error checks at this point. For example, if civ_engage &lt; 1</span>
  <span class="co"># or &gt; 6, then something has gone very wrong.</span>
  
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>z_age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">primary_06</span>, <span class="va">treatment</span>, <span class="va">sex</span>, <span class="va">civ_engage</span>, <span class="va">voter_class</span>, <span class="va">z_age</span><span class="op">)</span></code></pre></div>
<p>Let’s inspect our object:</p>
<div class="sourceCode" id="cb765"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">object_1</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 6
##   primary_06 treatment  sex    civ_engage voter_class    z_age
##        &lt;int&gt; &lt;fct&gt;      &lt;chr&gt;       &lt;int&gt; &lt;fct&gt;          &lt;dbl&gt;
## 1          0 Civic Duty Male            4 Sometimes Vote 1.05 
## 2          0 Civic Duty Female          4 Sometimes Vote 0.638
## 3          1 Hawthorne  Male            4 Sometimes Vote 0.361</code></pre>
<p>Great! Now, we will create our first model: the relationship between <code>primary_06</code>, which represents whether a citizen voted or not, against sex and treatment.</p>
</div>
<div id="primary_06-treatment-sex" class="section level3" number="11.2.2">
<h3>
<span class="header-section-number">11.2.2</span> primary_06 ~ treatment + sex<a class="anchor" aria-label="anchor" href="#primary_06-treatment-sex"><i class="fas fa-link"></i></a>
</h3>
<p>In this section, we will look at the relationship between primary voting and treatment + sex.</p>
<p><em>The math:</em></p>
<p>Without variable names:</p>
<p><span class="math display">\[ y_{i} = \beta_{0} + \beta_{1}x_{i, 1} + \beta_{2}x_{i,2} ... + \beta_{n}x_{i,n} + \epsilon_{i} \]</span>
With variable names:</p>
<p><span class="math display">\[ y_{i} = \beta_{0} + \beta_{1}civic\_duty_i + \beta_{2}hawthorne_i + \beta_{3}self_i + \beta_{4}neighbors_i + \beta_{5}male_i + \epsilon_{i} \]</span></p>
<p>There are two ways to formalize the model used in <code>model_1</code>: with and without the variable names. The former is related to the concept of Justice as we acknowledge that the model is constructed via the linear sum of <code>n</code> parameters times the value for <code>n</code> variables, along with an error term. In other words, it is a linear model. The only other model we have learned this semester is a logistic model, but there are other kinds of models, each defined by the mathematics and the assumptions about the error term.
The second type of formal notation, more associated with the virtue Courage, includes the actual variable names we are using. The trickiest part is the transformation of character/factor variables into indicator variables, meaning variables with 0/1 values. Because <code>treatment</code> has 5 levels, we need 4 indicator variables. The fifth level — which, by default, is the first variable alphabetically (for character variables) or the first level (for factor variables) — is incorporated in the intercept.</p>
<p>Let’s translate the model into code.</p>
<div class="sourceCode" id="cb767"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">model_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">object_1</span>,
                  formula <span class="op">=</span> <span class="va">primary_06</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">sex</span>,
                  refresh <span class="op">=</span> <span class="fl">0</span>,
                  seed <span class="op">=</span> <span class="fl">987</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb768"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://docs.ropensci.org/skimr/reference/print.html">print</a></span><span class="op">(</span><span class="va">model_1</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## stan_glm
##  family:       gaussian [identity]
##  formula:      primary_06 ~ treatment + sex
##  observations: 344084
##  predictors:   6
## ------
##                     Median MAD_SD
## (Intercept)         0.291  0.001 
## treatmentCivic Duty 0.018  0.003 
## treatmentHawthorne  0.026  0.003 
## treatmentSelf       0.048  0.002 
## treatmentNeighbors  0.081  0.003 
## sexMale             0.012  0.002 
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 0.464  0.001 
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p>We will now create a table that nicely formats the results of <code>fit_1</code> using the <code><a href="http://www.danieldsjoberg.com/gtsummary//reference/tbl_regression.html">tbl_regression()</a></code> function from the <strong>gtsummary</strong> package. It will also display the associated 95% confidence interval for each coefficient.</p>
<div class="sourceCode" id="cb770"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="http://www.danieldsjoberg.com/gtsummary//reference/tbl_regression.html">tbl_regression</a></span><span class="op">(</span><span class="va">model_1</span>, 
               intercept <span class="op">=</span> <span class="cn">TRUE</span>, 
               estimate_fun <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="http://www.danieldsjoberg.com/gtsummary//reference/style_sigfig.html">style_sigfig</a></span><span class="op">(</span><span class="va">x</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  
  <span class="co"># Using Beta as the name of the parameter column is weird.</span>
  
  <span class="fu"><a href="http://www.danieldsjoberg.com/gtsummary//reference/as_gt.html">as_gt</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/gt/man/tab_header.html">tab_header</a></span><span class="op">(</span>title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/gt/man/md.html">md</a></span><span class="op">(</span><span class="st">"**Likelihood of Voting in the Next Election**"</span><span class="op">)</span>,
             subtitle <span class="op">=</span> <span class="st">"How Treatment Assignment and Age Predict Likelihood of Voting"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/gt/man/tab_source_note.html">tab_source_note</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/gt/man/md.html">md</a></span><span class="op">(</span><span class="st">"Source: Gerber, Green, and Larimer (2008)"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/gt/man/cols_label.html">cols_label</a></span><span class="op">(</span>estimate <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/gt/man/md.html">md</a></span><span class="op">(</span><span class="st">"**Parameter**"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#tmtipirizw .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#tmtipirizw .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#tmtipirizw .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#tmtipirizw .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#tmtipirizw .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tmtipirizw .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#tmtipirizw .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#tmtipirizw .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#tmtipirizw .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#tmtipirizw .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#tmtipirizw .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#tmtipirizw .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#tmtipirizw .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#tmtipirizw .gt_from_md > :first-child {
  margin-top: 0;
}

#tmtipirizw .gt_from_md > :last-child {
  margin-bottom: 0;
}

#tmtipirizw .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#tmtipirizw .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#tmtipirizw .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#tmtipirizw .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#tmtipirizw .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#tmtipirizw .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#tmtipirizw .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#tmtipirizw .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#tmtipirizw .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#tmtipirizw .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#tmtipirizw .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#tmtipirizw .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#tmtipirizw .gt_left {
  text-align: left;
}

#tmtipirizw .gt_center {
  text-align: center;
}

#tmtipirizw .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#tmtipirizw .gt_font_normal {
  font-weight: normal;
}

#tmtipirizw .gt_font_bold {
  font-weight: bold;
}

#tmtipirizw .gt_font_italic {
  font-style: italic;
}

#tmtipirizw .gt_super {
  font-size: 65%;
}

#tmtipirizw .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="tmtipirizw" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><div class="inline-table"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style><strong>Likelihood of Voting in the Next Election</strong></th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>How Treatment Assignment and Age Predict Likelihood of Voting</th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Parameter</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">
<strong>95% CI</strong><sup class="gt_footnote_marks">1</sup>
</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left">(Intercept)</td>
      <td class="gt_row gt_center">0.291</td>
      <td class="gt_row gt_center">0.288, 0.293</td>
    </tr>
<tr>
<td class="gt_row gt_left">treatment</td>
      <td class="gt_row gt_center"></td>
      <td class="gt_row gt_center"></td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Control</td>
      <td class="gt_row gt_center">—</td>
      <td class="gt_row gt_center">—</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Civic Duty</td>
      <td class="gt_row gt_center">0.018</td>
      <td class="gt_row gt_center">0.013, 0.023</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Hawthorne</td>
      <td class="gt_row gt_center">0.026</td>
      <td class="gt_row gt_center">0.021, 0.031</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Self</td>
      <td class="gt_row gt_center">0.048</td>
      <td class="gt_row gt_center">0.044, 0.054</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Neighbors</td>
      <td class="gt_row gt_center">0.081</td>
      <td class="gt_row gt_center">0.076, 0.087</td>
    </tr>
<tr>
<td class="gt_row gt_left">sex</td>
      <td class="gt_row gt_center"></td>
      <td class="gt_row gt_center"></td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Female</td>
      <td class="gt_row gt_center">—</td>
      <td class="gt_row gt_center">—</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Male</td>
      <td class="gt_row gt_center">0.012</td>
      <td class="gt_row gt_center">0.009, 0.015</td>
    </tr>
</tbody>
<tfoot class="gt_sourcenotes"><tr>
<td class="gt_sourcenote" colspan="3">Source: Gerber, Green, and Larimer (2008)</td>
    </tr></tfoot>
<tfoot><tr class="gt_footnotes">
<td colspan="3">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks"><em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br></p>
      </td>
    </tr></tfoot>
</table></div></div>
<p>Interpretation:
* The intercept of this model is the expected value of the probability of someone voting in the 2006 primary given that they are part of the control group and are female. In this case, we estimate that women in the control group will vote ~29% of the time.
* The coefficient for <code>sexMale</code> indicates the difference in likelihood of voting between a male and female. In other words, when comparing men and women, the 0.012 implies that men are ~1.2% more likely to vote than women. Note that, because this is a linear model with no interactions between sex and other variables, this 1.2% difference applies to any male, regardless of the treatment he received. We are 95% certain that this difference is between 0.9% of 1.5%. Because sex can
not be manipulated (by assumption), we should not use a causal interpretation of the 1.2%.
* The coefficients of the treatments, on the other hand, do have a causal interpretation. For a single individual, of either sex, being sent the Self postcard increases your probability of voting by 4.8%. We are 95% certain that the true value for the average treatment effect of Self postcards is between 4.4% and 5.4%. It appears that the <code>Neighbors</code> treatment is the most effective at ~8.1% and <code>Civic Duty</code> is the least effective at ~1.8%.</p>
</div>
<div id="primary_06-z_age-sex-treatment-voter_class-voter_classtreatment" class="section level3" number="11.2.3">
<h3>
<span class="header-section-number">11.2.3</span> primary_06 ~ z_age + sex + treatment + voter_class + voter_class*treatment<a class="anchor" aria-label="anchor" href="#primary_06-z_age-sex-treatment-voter_class-voter_classtreatment"><i class="fas fa-link"></i></a>
</h3>
<p>It is time to look at interactions! Create another model named <code>fit_2</code> that estimates <code>primary_06</code> as a function of <code>z_age</code>, <code>sex</code>, <code>treatment</code>, <code>voter_class</code>, and the interaction between treatment and voter classification.</p>
<p>The math:
<span class="math display">\[y_{i} = \beta_{0} + \beta_{1}z\_age + \beta_{2}male_i + \beta_{3}civic\_duty_i + \\ \beta_{4}hawthorne_i + \beta_{5}self_i + \beta_{6}neighbors_i + \\ \beta_{7}Sometimes\ vote_i + \beta_{8}Always\ vote_i + \\ \beta_{9}civic\_duty_i Sometimes\ vote_i + \beta_{10}hawthorne_i Sometimes\ vote_i + \\ \beta_{11}self_i Sometimes\ vote_i + \beta_{11}neighbors_i Sometimes\ vote_i + \\ \beta_{12}civic\_duty_i Always\ vote_i + \beta_{13}hawthorne_i Always\ vote_i + \\ \beta_{14}self_i Always\ vote_i + \beta_{15}neighbors_i Always\ vote_i + \epsilon_{i}\]</span>
Translate into code:</p>
<div class="sourceCode" id="cb771"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">object_1</span>,
                  formula <span class="op">=</span> <span class="va">primary_06</span> <span class="op">~</span> <span class="va">z_age</span> <span class="op">+</span> <span class="va">sex</span> <span class="op">+</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">voter_class</span> <span class="op">+</span> 
                            <span class="va">treatment</span><span class="op">*</span><span class="va">voter_class</span>,
                  family <span class="op">=</span> <span class="va">gaussian</span>,
                  refresh <span class="op">=</span> <span class="fl">0</span>,
                  seed <span class="op">=</span> <span class="fl">789</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb772"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://docs.ropensci.org/skimr/reference/print.html">print</a></span><span class="op">(</span><span class="va">fit_2</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## stan_glm
##  family:       gaussian [identity]
##  formula:      primary_06 ~ z_age + sex + treatment + voter_class + treatment * 
##     voter_class
##  observations: 344084
##  predictors:   17
## ------
##                                               Median MAD_SD
## (Intercept)                                    0.153  0.003
## z_age                                          0.035  0.001
## sexMale                                        0.008  0.002
## treatmentCivic Duty                            0.010  0.007
## treatmentHawthorne                             0.008  0.007
## treatmentSelf                                  0.024  0.007
## treatmentNeighbors                             0.044  0.007
## voter_classSometimes Vote                      0.114  0.003
## voter_classAlways Vote                         0.294  0.004
## treatmentCivic Duty:voter_classSometimes Vote  0.014  0.007
## treatmentHawthorne:voter_classSometimes Vote   0.019  0.007
## treatmentSelf:voter_classSometimes Vote        0.030  0.008
## treatmentNeighbors:voter_classSometimes Vote   0.042  0.008
## treatmentCivic Duty:voter_classAlways Vote    -0.001  0.009
## treatmentHawthorne:voter_classAlways Vote      0.025  0.009
## treatmentSelf:voter_classAlways Vote           0.025  0.009
## treatmentNeighbors:voter_classAlways Vote      0.046  0.009
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 0.451  0.001 
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p>As we did with our first model, create a regression table to observe our findings:</p>
<div class="sourceCode" id="cb774"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="http://www.danieldsjoberg.com/gtsummary//reference/tbl_regression.html">tbl_regression</a></span><span class="op">(</span><span class="va">fit_2</span>, 
               intercept <span class="op">=</span> <span class="cn">TRUE</span>, 
               estimate_fun <span class="op">=</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="fu"><a href="http://www.danieldsjoberg.com/gtsummary//reference/style_sigfig.html">style_sigfig</a></span><span class="op">(</span><span class="va">x</span>, digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="http://www.danieldsjoberg.com/gtsummary//reference/as_gt.html">as_gt</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/gt/man/tab_header.html">tab_header</a></span><span class="op">(</span>title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/gt/man/md.html">md</a></span><span class="op">(</span><span class="st">"**Likelihood of Voting in the Next Election**"</span><span class="op">)</span>,
             subtitle <span class="op">=</span> <span class="st">"How Treatment Assignment and Other Variables Predict Likelihood of Voting"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/gt/man/tab_source_note.html">tab_source_note</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/gt/man/md.html">md</a></span><span class="op">(</span><span class="st">"Source: Gerber, Green, and Larimer (2008)"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/gt/man/cols_label.html">cols_label</a></span><span class="op">(</span>estimate <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/gt/man/md.html">md</a></span><span class="op">(</span><span class="st">"**Parameter**"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#truqukjwbl .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#truqukjwbl .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#truqukjwbl .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#truqukjwbl .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#truqukjwbl .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#truqukjwbl .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#truqukjwbl .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#truqukjwbl .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#truqukjwbl .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#truqukjwbl .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#truqukjwbl .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#truqukjwbl .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#truqukjwbl .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#truqukjwbl .gt_from_md > :first-child {
  margin-top: 0;
}

#truqukjwbl .gt_from_md > :last-child {
  margin-bottom: 0;
}

#truqukjwbl .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#truqukjwbl .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#truqukjwbl .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#truqukjwbl .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#truqukjwbl .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#truqukjwbl .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#truqukjwbl .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#truqukjwbl .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#truqukjwbl .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#truqukjwbl .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#truqukjwbl .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#truqukjwbl .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#truqukjwbl .gt_left {
  text-align: left;
}

#truqukjwbl .gt_center {
  text-align: center;
}

#truqukjwbl .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#truqukjwbl .gt_font_normal {
  font-weight: normal;
}

#truqukjwbl .gt_font_bold {
  font-weight: bold;
}

#truqukjwbl .gt_font_italic {
  font-style: italic;
}

#truqukjwbl .gt_super {
  font-size: 65%;
}

#truqukjwbl .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="truqukjwbl" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><div class="inline-table"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style><strong>Likelihood of Voting in the Next Election</strong></th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>How Treatment Assignment and Other Variables Predict Likelihood of Voting</th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Parameter</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">
<strong>95% CI</strong><sup class="gt_footnote_marks">1</sup>
</th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left">(Intercept)</td>
      <td class="gt_row gt_center">0.153</td>
      <td class="gt_row gt_center">0.147, 0.159</td>
    </tr>
<tr>
<td class="gt_row gt_left">z_age</td>
      <td class="gt_row gt_center">0.035</td>
      <td class="gt_row gt_center">0.033, 0.037</td>
    </tr>
<tr>
<td class="gt_row gt_left">sex</td>
      <td class="gt_row gt_center"></td>
      <td class="gt_row gt_center"></td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Female</td>
      <td class="gt_row gt_center">—</td>
      <td class="gt_row gt_center">—</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Male</td>
      <td class="gt_row gt_center">0.008</td>
      <td class="gt_row gt_center">0.005, 0.011</td>
    </tr>
<tr>
<td class="gt_row gt_left">treatment</td>
      <td class="gt_row gt_center"></td>
      <td class="gt_row gt_center"></td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Control</td>
      <td class="gt_row gt_center">—</td>
      <td class="gt_row gt_center">—</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Civic Duty</td>
      <td class="gt_row gt_center">0.010</td>
      <td class="gt_row gt_center">-0.003, 0.022</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Hawthorne</td>
      <td class="gt_row gt_center">0.008</td>
      <td class="gt_row gt_center">-0.006, 0.021</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Self</td>
      <td class="gt_row gt_center">0.024</td>
      <td class="gt_row gt_center">0.011, 0.037</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Neighbors</td>
      <td class="gt_row gt_center">0.044</td>
      <td class="gt_row gt_center">0.031, 0.057</td>
    </tr>
<tr>
<td class="gt_row gt_left">voter_class</td>
      <td class="gt_row gt_center"></td>
      <td class="gt_row gt_center"></td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Rarely Vote</td>
      <td class="gt_row gt_center">—</td>
      <td class="gt_row gt_center">—</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Sometimes Vote</td>
      <td class="gt_row gt_center">0.114</td>
      <td class="gt_row gt_center">0.108, 0.120</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Always Vote</td>
      <td class="gt_row gt_center">0.294</td>
      <td class="gt_row gt_center">0.287, 0.301</td>
    </tr>
<tr>
<td class="gt_row gt_left">treatment * voter_class</td>
      <td class="gt_row gt_center"></td>
      <td class="gt_row gt_center"></td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Civic Duty * Sometimes Vote</td>
      <td class="gt_row gt_center">0.014</td>
      <td class="gt_row gt_center">0.000, 0.029</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Hawthorne * Sometimes Vote</td>
      <td class="gt_row gt_center">0.019</td>
      <td class="gt_row gt_center">0.004, 0.034</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Self * Sometimes Vote</td>
      <td class="gt_row gt_center">0.030</td>
      <td class="gt_row gt_center">0.015, 0.045</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Neighbors * Sometimes Vote</td>
      <td class="gt_row gt_center">0.042</td>
      <td class="gt_row gt_center">0.028, 0.056</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Civic Duty * Always Vote</td>
      <td class="gt_row gt_center">-0.001</td>
      <td class="gt_row gt_center">-0.018, 0.016</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Hawthorne * Always Vote</td>
      <td class="gt_row gt_center">0.025</td>
      <td class="gt_row gt_center">0.009, 0.042</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Self * Always Vote</td>
      <td class="gt_row gt_center">0.025</td>
      <td class="gt_row gt_center">0.009, 0.042</td>
    </tr>
<tr>
<td class="gt_row gt_left" style="text-align: left; text-indent: 10px;">Neighbors * Always Vote</td>
      <td class="gt_row gt_center">0.046</td>
      <td class="gt_row gt_center">0.030, 0.063</td>
    </tr>
</tbody>
<tfoot class="gt_sourcenotes"><tr>
<td class="gt_sourcenote" colspan="3">Source: Gerber, Green, and Larimer (2008)</td>
    </tr></tfoot>
<tfoot><tr class="gt_footnotes">
<td colspan="3">
        <p class="gt_footnote">
          <sup class="gt_footnote_marks"><em>1</em>
          </sup>
           
          CI = Confidence Interval
          <br></p>
      </td>
    </tr></tfoot>
</table></div></div>
<p>Now that we have a summarized visual for our data, let’s interpret the findings:
* The intercept of <code>fit_2</code> is the expected probability of voting in the upcoming election for a woman of average age (~ 50 years old in this data), who is assigned to the Control group, and is a Rarely Voter. The
estimate is 15.3% with a 95% confidence interval of 14.7% to 15.9%.
* The coefficient of z_age, 0.035, implies a change of ~ 3.5% in likelihood of voting for each increment of one standard deviation (~ 14.45
years). For example: when comparing someone 50 years old with someone 65, the latter is about 3.5% more likely to vote.
* Exposure to the Neighbors treatment shows a ~4.4% increase in voting likelihood for someone in the Rarely Vote category. Because of random assignment of treatment, we can interpret that coefficient as an estimate
of the average treatment effect.
* If someone were from a different voter classification, the calculation is more complex because we need to account for the interaction term. For example, for individuals who Sometimes Vote, the treatment effect of Neighbors is 8.6%. For Always Vote Neighbors, it is 9.0%.</p>
</div>
</div>
<div id="temperance-8" class="section level2" number="11.3">
<h2>
<span class="header-section-number">11.3</span> Temperance<a class="anchor" aria-label="anchor" href="#temperance-8"><i class="fas fa-link"></i></a>
</h2>
<div class="figure">
<span id="fig:unnamed-chunk-643"></span>
<img src="other/images/Temperance.jpg" alt="Temperance" width="100%"><p class="caption">
FIGURE 11.4: Temperance
</p>
</div>
<p>Finally, let’s remember the virtue of Temperance. The gist of temperance is: be humble with our inferences, as our inferences are always, certainly, and unfortunately not going to match the real world. How does this apply to our shaming scenario?</p>
<p>Recall our initial question: <em>What is the causal effect, on the likelihood of voting, of different postcards on voters of different levels of political engagement?</em></p>
<p>To answer the question, we want to look at different average treatment effects. In the real world, the treatment effect for person A is almost always different than the treatment effect for person B.</p>
<p>Regardless, let’s create a plot that displays the posterior probability distributions of the average treatment effects for men of average age across all combinations of 4 treatments and 3 voter classifications:</p>
<div class="sourceCode" id="cb775"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Recall that the z-scored age of 0 is ~50 yrs. old in this case. We could look</span>
<span class="co"># at lots of ages and both Male and Female. But that would not change our</span>
<span class="co"># estimates of the treatment effects. The model is linear, so terms associated</span>
<span class="co"># with z_age and sex disappear when we do the subtraction. This is one of the</span>
<span class="co"># great advantages of linear models.</span>

<span class="va">sex</span> <span class="op">&lt;-</span> <span class="st">"Male"</span>
<span class="va">z_age</span> <span class="op">&lt;-</span> <span class="fl">0</span>
<span class="va">treatment</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Control"</span>,
               <span class="st">"Civic Duty"</span>,
               <span class="st">"Hawthorne"</span>,
               <span class="st">"Self"</span>,
               <span class="st">"Neighbors"</span><span class="op">)</span>
<span class="va">voter_class</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Always Vote"</span>,
                 <span class="st">"Sometimes Vote"</span>,
                 <span class="st">"Rarely Vote"</span><span class="op">)</span>

<span class="co"># This question requires quite the complicated tibble! Speaking both</span>
<span class="co"># hypothetically and from experience, keeping track of loads of nondescript</span>
<span class="co"># column names after running posterior_epred() while doing ATE calculations</span>
<span class="co"># leaves you prone to simple, but critical, errors. expand_grid() was created</span>
<span class="co"># for cases just like this - we want all combinations of treatments and voter</span>
<span class="co"># classifications in the same way that our model displays the interaction term</span>
<span class="co"># parameters.</span>

<span class="va">newobs</span> <span class="op">&lt;-</span> <span class="fu">expand_grid</span><span class="op">(</span><span class="va">sex</span>, <span class="va">z_age</span>, <span class="va">treatment</span>, <span class="va">voter_class</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  
  <span class="co"># This is a handy setup for the following piece of code that allows us to</span>
  <span class="co"># mutate the ATE columns with self-contained variable names. This is what</span>
  <span class="co"># helps to ensure that the desired calculations are indeed being done. If you</span>
  <span class="co"># aren't familiar, check out the help page for paste() at `?paste`.</span>
  
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">treatment</span>, <span class="va">voter_class</span>, sep <span class="op">=</span> <span class="st">"_"</span><span class="op">)</span><span class="op">)</span>

<span class="va">pe</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html">posterior_epred</a></span><span class="op">(</span><span class="va">fit_2</span>,
                        newdata <span class="op">=</span> <span class="va">newobs</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://tibble.tidyverse.org/reference/as_tibble.html">as_tibble</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  
  <span class="co"># Here we can stick the names that we created in newobs onto the otherwise</span>
  <span class="co"># unfortunately named posterior_epred() output. </span>
  
  <span class="fu">set_names</span><span class="op">(</span><span class="va">newobs</span><span class="op">$</span><span class="va">names</span><span class="op">)</span>

<span class="va">plot_data</span> <span class="op">&lt;-</span> <span class="va">pe</span> <span class="op">%&gt;%</span> 
  
  <span class="co"># Using our cleaned naming system, ATE calculations are simple enough. Note</span>
  <span class="co"># how much easier the code reads because we have taken the trouble to line up</span>
  <span class="co"># the columns.</span>
  
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>`Always Civic-Duty`    <span class="op">=</span> <span class="va">`Civic Duty_Always Vote`</span>     <span class="op">-</span> <span class="va">`Control_Always Vote`</span>,
         `Always Hawthorne`     <span class="op">=</span> <span class="va">`Hawthorne_Always Vote`</span>      <span class="op">-</span> <span class="va">`Control_Always Vote`</span>,
         `Always Self`          <span class="op">=</span> <span class="va">`Self_Always Vote`</span>           <span class="op">-</span> <span class="va">`Control_Always Vote`</span>,
         `Always Neighbors`     <span class="op">=</span> <span class="va">`Neighbors_Always Vote`</span>      <span class="op">-</span> <span class="va">`Control_Always Vote`</span>,
         `Sometimes Civic-Duty` <span class="op">=</span> <span class="va">`Civic Duty_Sometimes Vote`</span>  <span class="op">-</span> <span class="va">`Control_Sometimes Vote`</span>,
         `Sometimes Hawthorne`  <span class="op">=</span> <span class="va">`Hawthorne_Sometimes Vote`</span>   <span class="op">-</span> <span class="va">`Control_Sometimes Vote`</span>,
         `Sometimes Self`       <span class="op">=</span> <span class="va">`Self_Sometimes Vote`</span>        <span class="op">-</span> <span class="va">`Control_Sometimes Vote`</span>,
         `Sometimes Neighbors`  <span class="op">=</span> <span class="va">`Neighbors_Sometimes Vote`</span>   <span class="op">-</span> <span class="va">`Control_Sometimes Vote`</span>,
         `Rarely Civic-Duty`    <span class="op">=</span> <span class="va">`Civic Duty_Rarely Vote`</span>     <span class="op">-</span> <span class="va">`Control_Rarely Vote`</span>,
         `Rarely Hawthorne`     <span class="op">=</span> <span class="va">`Hawthorne_Rarely Vote`</span>      <span class="op">-</span> <span class="va">`Control_Rarely Vote`</span>,
         `Rarely Self`          <span class="op">=</span> <span class="va">`Self_Rarely Vote`</span>           <span class="op">-</span> <span class="va">`Control_Rarely Vote`</span>,
         `Rarely Neighbors`     <span class="op">=</span> <span class="va">`Neighbors_Rarely Vote`</span>      <span class="op">-</span> <span class="va">`Control_Rarely Vote`</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  
  <span class="co"># This is a critical step, we need to be able to reference voter</span>
  <span class="co"># classification separately from the treatment assignment, so pivoting in the</span>
  <span class="co"># following manner reconstructs the relevant columns for each of these</span>
  <span class="co"># individually. </span>
  
  <span class="fu">pivot_longer</span><span class="op">(</span>names_to <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Voter Class"</span>, <span class="st">"Group"</span><span class="op">)</span>,
               names_sep <span class="op">=</span> <span class="st">" "</span>,
               values_to <span class="op">=</span> <span class="st">"values"</span>,
               cols <span class="op">=</span> <span class="va">`Always Civic-Duty`</span><span class="op">:</span><span class="va">`Rarely Neighbors`</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  
    <span class="co"># Reordering the factors of voter classification forces them to be displayed</span>
    <span class="co"># in a sensible order in the plot later.</span>
  
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>`Voter Class` <span class="op">=</span> <span class="fu">fct_relevel</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">`Voter Class`</span><span class="op">)</span>,
                                     <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Rarely"</span>,
                                       <span class="st">"Sometimes"</span>,
                                       <span class="st">"Always"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="va">plot_data</span>  <span class="op">%&gt;%</span> 
  
  <span class="co"># Reordering the y axis values allows a smoother visual interpretation - </span>
  <span class="co"># you can see the treatments in sequential ATE.</span>
  
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">values</span>, y <span class="op">=</span> <span class="fu">fct_reorder</span><span class="op">(</span><span class="va">Group</span>, <span class="va">values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  
  <span class="co"># position = "dodge" is the only sure way to see all 3 treatment distributions</span>
  <span class="co"># identity, single, or any others drop "Sometimes" - topic for further study</span>
  
    <span class="fu"><a href="http://mjskay.github.io/ggdist/reference/stat_sample_slabinterval.html">stat_slab</a></span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>fill <span class="op">=</span> <span class="va">`Voter Class`</span><span class="op">)</span>,
              position <span class="op">=</span> <span class="st">'dodge'</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://rdrr.io/pkg/ggthemes/man/scale_calc.html">scale_fill_calc</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  
    <span class="co"># more frequent breaks on the x-axis provides a better reader interpretation</span>
    <span class="co"># of the the shift across age groups, as opposed to intervals of 10%</span>
    
    <span class="fu">scale_x_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span>accuracy <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,
                       breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">0.05</span>, <span class="fl">0.11</span>, <span class="fl">0.01</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Treatment Effects on The Probability of Voting"</span>,
         subtitle <span class="op">=</span> <span class="st">"Postcards work less well on those who rarely vote"</span>,
         y <span class="op">=</span> <span class="st">"Postcard Type"</span>,
         x <span class="op">=</span> <span class="st">"Average Treatment Effect"</span>,
         caption <span class="op">=</span> <span class="st">"Source: Gerber, Green, and Larimer (2008)"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu"><a href="https://rdrr.io/pkg/ggthemes/man/theme_clean.html">theme_clean</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme</span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/plot_2-1.png" width="100%"></div>
<p>This is interesting! It shows us a few valuable bits of information:</p>
<ul>
<li>We are interested in the average treatment effect of postcards. There are 4 different postcards, each of which can be compared to what would have happened if the voter did not receive any postcard.</li>
<li>These four treatment effects, however, are heterogeneous. They vary depending on an individual’s voting history, which we organize into three categories: Rarely Vote, Sometimes Vote and Always Vote. So, we have 12 different
average treatment effects, one for each possible combination of postcard and voting history.</li>
<li>For each of these combinations, the graphic shows our posterior distribution.</li>
<li>Consider the highest yellow distribution, which is the posterior distribution for the average treatment effect of receiving the Neighbors postcard (compared to not getting a postcard) for Always Voters. The posterior is centered around 9% with a 95% confidence interval of, roughly, 8% to 10%.</li>
<li>Overall, the Civic Duty and Hawthorne postcards had small average treatment effects, across all three categories of voter. The causal effect on Rarely Voters was much smaller, regardless of treatment. It was also much less precisely estimated because there were many fewer Rarely Voters in the data.
*The best way to increase turnover, assuming there are limits to how many postcards you can send, is to focus on Sometimes/Always voters and to use the Neighbors postcard.</li>
</ul>
<p>If we wanted to increase voter turnout, then, we would focus our efforts on the Neighbors postcard for citizens who already demonstrate a tendency to vote.</p>
<p>Does this mean this is guaranteed to work? Unfortunately, no matter how hard we try, <em>we cannot predict the future</em>. Though we now have conclusions about how shaming impacted voters in the 2006 primary elections, we do not have the confidence to say that what worked or didn’t work then would work now.</p>
<p>For instance, perhaps the impact of your neighbors knowing your voting history is greater in the midst of a pandemic, where you may be locked inside with few interactions outside of your immediate proximity. Perhaps the opposite is true. These <em>unknown unknowns</em> cannot be accounted for in our models. We cannot predict a pandemic, nor can we predict how this will change the way that people vote or respond to fliers.</p>
<p>There is also the issue of representativeness. Do the voters of the 2006 primary election (who have already demonstrated a willingness to vote in the 2004 primary election) truly represent the people voting in <strong>our</strong> gubernatorial election?</p>
<p>These complications are why we must make inferences with a grain of salt. That is not to say that all data science is unhelpful! On the contrary, acknowledging our deficits will only make our inferences (and the actions we take because of them) stronger.</p>
<!-- What we need to add: Preceptor table, causal explanation, math before models, posterior_epred. -->
</div>
<div id="summary-11" class="section level2" number="11.4">
<h2>
<span class="header-section-number">11.4</span> Summary<a class="anchor" aria-label="anchor" href="#summary-11"><i class="fas fa-link"></i></a>
</h2>
<p><em>Key commands</em>:
* Use the <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> function from the <strong>broom.mixed</strong> package to make models with <span class="math inline">\(N\)</span> parameters easier to interpret.
* A function we are familiar with, <code><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm()</a></code>, is used to create models with <span class="math inline">\(N\)</span> parameters.</p>
<p><em>Remember</em>:
* It is important to remember that the data does not equal the truth.
* The population we would like to make inferences about <em>is not the population for which we have data</em>. It is a matter of wisdom whether the data we do have maps closely enough to the population we are studying.
* When dealing with models with many parameters, double check that you know how to find the true slope and intercepts — often, this requires adding numerous values to the coefficient you are studying.</p>

<!-- Fix images in UNIX section so that they use 1005 instead, to match the new text. -->
<!-- Explain importance of scripting versus click-and-drag and copy-pasting. Add section about useful keyboard shortcuts. -->
<!-- Add material about file organization. -->
<!-- Find a place to mention all the high quality sources listed below. Maybe with a webshot of their title pages?  -->
<!-- Happy Git for the R User. -->
<!-- Anything associated with RStudio. -->
<!-- [The UNIX Workbench](https://seankross.com/the-unix-workbench/), but with all the work done form the terminal window in RStudio.  -->
<!-- [What They Forgot to Teach You About R](https://rstats.wtf/) -->
<!-- https://usethis.r-lib.org/articles/articles/usethis-setup. Might just pull out the key sections of this. We can't just link to it since some of it --- like devtools --- is too confusing. -->
<!-- https://merely-useful.github.io/py-rse/ -->
<!-- Consider making the **fs** package a major part of the presentation. This helps avoid dealing with cross-OS issues ourselves. Also teaches students that there is more than one way to interact with the file system. -->
<!-- Add some optional videos, especially the ones from RStudio which give nice tours of RStudio stuff. -->
<!-- Buttons we press should be bolded, not wrapped with backticks. -->
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="five-parameters.html"><span class="header-section-number">10</span> Five Parameters</a></div>
<div class="next"><a href="tools.html">Tools</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#n-parameters"><span class="header-section-number">11</span> N Parameters</a></li>
<li>
<a class="nav-link" href="#wisdom-8"><span class="header-section-number">11.1</span> Wisdom</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#eda-of-shaming"><span class="header-section-number">11.1.1</span> EDA of shaming</a></li>
<li><a class="nav-link" href="#population-1"><span class="header-section-number">11.1.2</span> Population</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#justice-and-courage-1"><span class="header-section-number">11.2</span> Justice and Courage</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#set-up"><span class="header-section-number">11.2.1</span> Set-up</a></li>
<li><a class="nav-link" href="#primary_06-treatment-sex"><span class="header-section-number">11.2.2</span> primary_06 ~ treatment + sex</a></li>
<li><a class="nav-link" href="#primary_06-z_age-sex-treatment-voter_class-voter_classtreatment"><span class="header-section-number">11.2.3</span> primary_06 ~ z_age + sex + treatment + voter_class + voter_class*treatment</a></li>
</ul>
</li>
<li><a class="nav-link" href="#temperance-8"><span class="header-section-number">11.3</span> Temperance</a></li>
<li><a class="nav-link" href="#summary-11"><span class="header-section-number">11.4</span> Summary</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/PPBDS/primer/blob/master/11-n-parameters.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/PPBDS/primer/edit/master/11-n-parameters.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Preceptor’s Primer for Bayesian Data Science</strong>" was written by David Kane. </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>
</html>
