<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 8 Three Parameters | Preceptor’s Primer for Bayesian Data Science</title>
<meta name="author" content="David Kane">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.2"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.8/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.5.1/tabs.js"></script><script src="libs/bs3compat-0.2.5.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script><script src="libs/plotly-binding-4.9.3/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet">
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script><script src="libs/rglWebGL-binding-0.106.8/rglWebGL.js"></script><link href="libs/rglwidgetClass-0.106.8/rgl.css" rel="stylesheet">
<script src="libs/rglwidgetClass-0.106.8/rglClass.min.js"></script><script src="libs/CanvasMatrix4-0.106.8/CanvasMatrix.min.js"></script><script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/mark.js@8.11.1/dist/mark.min.js"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Preceptor’s Primer for Bayesian Data Science</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Welcome</a></li>
<li><a class="" href="preamble.html">Preamble</a></li>
<li><a class="" href="getting-started.html">Getting Started</a></li>
<li><a class="" href="visualization.html"><span class="header-section-number">1</span> Visualization</a></li>
<li><a class="" href="wrangling.html"><span class="header-section-number">2</span> Wrangling</a></li>
<li><a class="" href="data.html"><span class="header-section-number">3</span> Data</a></li>
<li><a class="" href="rubin-causal-model.html"><span class="header-section-number">4</span> Rubin Causal Model</a></li>
<li><a class="" href="probability.html"><span class="header-section-number">5</span> Probability</a></li>
<li><a class="" href="one-parameter.html"><span class="header-section-number">6</span> One Parameter</a></li>
<li><a class="" href="two-parameters.html"><span class="header-section-number">7</span> Two Parameters</a></li>
<li><a class="active" href="three-parameters.html"><span class="header-section-number">8</span> Three Parameters</a></li>
<li><a class="" href="four-parameters.html"><span class="header-section-number">9</span> Four Parameters</a></li>
<li><a class="" href="five-parameters.html"><span class="header-section-number">10</span> Five Parameters</a></li>
<li><a class="" href="n-parameters.html"><span class="header-section-number">11</span> N Parameters</a></li>
<li><a class="" href="tools.html">Tools</a></li>
<li><a class="" href="functions.html">Functions</a></li>
<li><a class="" href="maps.html">Maps</a></li>
<li><a class="" href="ipums.html">IPUMS</a></li>
<li><a class="" href="animation.html">Animation</a></li>
<li><a class="" href="set-up-for-working-on-the-primer.html">Set Up for Working on The Primer</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/PPBDS/primer">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="three-parameters" class="section level1" number="8">
<h1>
<span class="header-section-number">8</span> Three Parameters<a class="anchor" aria-label="anchor" href="#three-parameters"><i class="fas fa-link"></i></a>
</h1>
<!-- Do Wisdom and Justice at the top. -->
<!-- DK: Where is the best place to modify income and discuss it? -->
<!-- DK: Review concept of dummy variables in the context of the intercept model with categorical predictor. Or not? -->
<p>Models have parameters. In Chapter <a href="one-parameter.html#one-parameter">6</a> we created models with a single parameter <span class="math inline">\(p\)</span>, the proportion of red beads in an urn. In Chapter <a href="two-parameters.html#two-parameters">7</a>, we used models with two parameters: <span class="math inline">\(\mu\)</span> (the average height in the population, generically known as a model “intercept”) and <span class="math inline">\(\sigma\)</span> (the variation in height in the population). Here — can you guess where this is going? — we will build models with three parameters: <span class="math inline">\(\sigma\)</span> (which serves the same role throughout the book) and two coefficients. In models which relate a continuous predictor to the outcome, those two parameters will be labeled <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. In models which estimate two averages, the parameters will be <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>. All this notation is confusing, not least because different academic fields use inconsistent schemes. Follow the Cardinal Virtues and tackle your problem step by step.</p>
<!-- DK: More detail? -->
<div id="wisdom-2" class="section level2" number="8.1">
<h2>
<span class="header-section-number">8.1</span> Wisdom<a class="anchor" aria-label="anchor" href="#wisdom-2"><i class="fas fa-link"></i></a>
</h2>
<p>Wisdom begins with considering the questions we desire to answer and the data set we are given.</p>
<div id="the-questions" class="section level3" number="8.1.1">
<h3>
<span class="header-section-number">8.1.1</span> The Questions<a class="anchor" aria-label="anchor" href="#the-questions"><i class="fas fa-link"></i></a>
</h3>
<p><em>What is the expected age of a Democrat at the train station?</em></p>
<p><em>In a group of three Democrats and three Republicans, what will the age difference be between the oldest Democrat and the youngest Republican?</em></p>
<p><em>What is the average treatment effect, of exposing people to Spanish-speakers, on their attitudes toward immigration?</em></p>
<p><em>What is the largest causal effect which still has a 1 in 10 chance of occurring?</em></p>
<!-- MM: clarify prior to question what q.4 is referring to, like causal effect of exposing people to spanish speakers on their attitudes toward immigration? -->
<p><em>What would you expect the income to be for a random 40 year old?</em></p>
<p><em>Among all people who have an income $100,000, what proportion are liberal?</em></p>
<p><em>Assume we have a group of eight people, two of whom make $100,000, two $200,000, two $300,000 and two $400,000. How many will be liberal?</em></p>
<p>After determining the questions we would like to answer, we must then consider ideally what data we would have to do so and make our preceptor table. In other words, for each individual in the population, what information do we need to answer each question. Look at the first question. Upon first glance, it appears that to answer this, we would like to have the age and party affiliation of those in population, and the same holds true for the second question. Therefore, we would need to have the columns of age and party affiliation in our preceptor table. The third and fourth question, however, would require individuals being exposed to Spanish-speakers and the their attitudes on immigration before and after the fact, so in our preceptor table, we would need the columns of attitude on immigration before and after being exposed to Spanish-speakers. Lastly, the fourth question would require income and age for every individual in the population, and the fifth and sixth would require knowing whether an individual is liberal or not as well as their income, so we would also need columns with information on income and if someone is liberal or not. Therefore, our preceptor table would appear as the following:</p>
<!-- MM: Make sample Preceptor Table -->
<p>Now that we have determined the data we would ideally have to answer the above questions, we have to take a look at the data set we have. To demonstrate modeling with three parameters, we will use the <code>trains</code> data set from the <strong>primer.data</strong> package.</p>
</div>
<div id="eda-for-trains" class="section level3" number="8.1.2">
<h3>
<span class="header-section-number">8.1.2</span> EDA for <code>trains</code><a class="anchor" aria-label="anchor" href="#eda-for-trains"><i class="fas fa-link"></i></a>
</h3>
<p><em>Always explore your data.</em> Recall the discussion from Chapter <a href="rubin-causal-model.html#rubin-causal-model">4</a>. <span class="citation"><a href="references.html#ref-enos2014" role="doc-biblioref">Enos</a> (<a href="references.html#ref-enos2014" role="doc-biblioref">2014</a>)</span> randomly placed Spanish-speaking confederates on nine train platforms around Boston, Massachusetts. Exposure to Spanish-speakers – the <code>treatment</code> – influenced attitudes toward immigration. These reactions were measured through changes in answers to three survey questions. Load the necessary libraries and look at the data.</p>
<div class="sourceCode" id="cb740"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">primer.data</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mc-stan.org/rstanarm/">rstanarm</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/skimr/">skimr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb741"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">glimpse</span><span class="op">(</span><span class="va">trains</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 115
## Columns: 15
## $ treatment           &lt;fct&gt; Treated, Treated, Treated, Treated, Control, Treat…
## $ att_start           &lt;dbl&gt; 11, 9, 3, 11, 8, 13, 13, 10, 12, 9, 10, 11, 13, 6,…
## $ att_end             &lt;dbl&gt; 11, 10, 5, 11, 5, 13, 13, 11, 12, 10, 9, 9, 13, 7,…
## $ gender              &lt;chr&gt; "Female", "Female", "Male", "Male", "Male", "Femal…
## $ race                &lt;chr&gt; "White", "White", "White", "White", "White", "Whit…
## $ liberal             &lt;lgl&gt; FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FAL…
## $ party               &lt;chr&gt; "Democrat", "Republican", "Democrat", "Democrat", …
## $ age                 &lt;int&gt; 31, 34, 63, 45, 55, 37, 53, 36, 54, 42, 33, 50, 24…
## $ income              &lt;dbl&gt; 135000, 105000, 135000, 300000, 135000, 87500, 875…
## $ line                &lt;chr&gt; "Framingham", "Framingham", "Framingham", "Framing…
## $ station             &lt;chr&gt; "Grafton", "Southborough", "Grafton", "Grafton", "…
## $ hisp_perc           &lt;dbl&gt; 0.026, 0.015, 0.019, 0.019, 0.019, 0.023, 0.030, 0…
## $ ideology_start      &lt;int&gt; 3, 4, 1, 4, 2, 5, 5, 4, 4, 4, 3, 5, 4, 1, 2, 2, 3,…
## $ ideology_end        &lt;int&gt; 3, 4, 2, 4, 2, 5, 5, 4, 3, 4, 3, 4, 4, 1, 2, 3, 3,…
## $ income_in_thousands &lt;dbl&gt; 135, 105, 135, 300, 135, 88, 88, 135, 105, 135, 10…</code></pre>
<p>The data include information about each respondent’s gender, political affiliations, age, income and so on. <code>treatment</code> indicates whether a subject was in the control or treatment group. The key outcomes are their attitudes toward immigration both before (<code>att_start</code>) and after (<code>att_end</code>) the experiment. We also have a measure of their ideology before and after the experiment, but there is little change. Type <code><a href="https://rdrr.io/pkg/primer.data/man/trains.html">?trains</a></code> to read the help page for more information about each variable.</p>
<p>Let’s restrict attention to a subset of the variables by recalling the Preceptor table we made. By that, we can determine that the variables <code>age</code>, <code>party</code>, <code>liberal</code> and <code>income</code> are relevant to the questions we seek to answer. This is because <code>age</code> is the age of the respondent, <code>party</code> is their political party affiliation, <code>liberal</code> is whether they are liberal or not, and <code>income</code> is the income of the respondent. Additionally, since <code>treatment</code> tells us whether the respondent was given the treatment of being exposed to Spanish-speakers in the train station and <code>att_end</code> tell us about the respondent’s attitude on immigration after the treatment, these are also variables of interest to us since they will be useful in answering some questions.</p>
<!-- MM: Incorporate lines 103-130 here -->
</div>
</div>
<div id="age-party" class="section level2" number="8.2">
<h2>
<span class="header-section-number">8.2</span> age ~ party<a class="anchor" aria-label="anchor" href="#age-party"><i class="fas fa-link"></i></a>
</h2>
<p>We want to build a model and then use that model to make claims about the world.</p>
<p><em>What is the expected age of a Democrat at the train station?</em></p>
<p><em>In a group of three Democrats and three Republicans, what will the age difference be between the oldest Democrat and the youngest Republican?</em></p>
<p>We can answer these and similar questions by creating a model that uses party affiliation to predict age</p>
<div id="wisdom-3" class="section level3" number="8.2.1">
<h3>
<span class="header-section-number">8.2.1</span> Wisdom<a class="anchor" aria-label="anchor" href="#wisdom-3"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-571"></span>
<img src="other/images/Wisdom.jpg" alt="Wisdom" width="100%"><p class="caption">
FIGURE 8.1: Wisdom
</p>
</div>
<p>Wisdom begins with a look at your data.</p>
<!-- Discuss to Preceptor Tables and ideal data to answer our questions -->
<div id="eda-for-trains-1" class="section level4" number="8.2.1.1">
<h4>
<span class="header-section-number">8.2.1.1</span> EDA for <code>trains</code><a class="anchor" aria-label="anchor" href="#eda-for-trains-1"><i class="fas fa-link"></i></a>
</h4>
<p><em>Always explore your data.</em> To demonstrate modeling with three parameters, we will use the <code>trains</code> data set from the <strong>primer.data</strong> package. Recall the discussion from Chapter <a href="rubin-causal-model.html#rubin-causal-model">4</a>. <span class="citation"><a href="references.html#ref-enos2014" role="doc-biblioref">Enos</a> (<a href="references.html#ref-enos2014" role="doc-biblioref">2014</a>)</span> randomly placed Spanish-speaking confederates on nine train platforms around Boston, Massachusetts. Exposure to Spanish-speakers – the <code>treatment</code> – influenced attitudes toward immigration. These reactions were measured through changes in answers to three survey questions. Load the necessary libraries and look at the data.</p>
<div class="sourceCode" id="cb743"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">primer.data</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://mc-stan.org/rstanarm/">rstanarm</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/skimr/">skimr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb744"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">glimpse</span><span class="op">(</span><span class="va">trains</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 115
## Columns: 15
## $ treatment           &lt;fct&gt; Treated, Treated, Treated, Treated, Control, Treat…
## $ att_start           &lt;dbl&gt; 11, 9, 3, 11, 8, 13, 13, 10, 12, 9, 10, 11, 13, 6,…
## $ att_end             &lt;dbl&gt; 11, 10, 5, 11, 5, 13, 13, 11, 12, 10, 9, 9, 13, 7,…
## $ gender              &lt;chr&gt; "Female", "Female", "Male", "Male", "Male", "Femal…
## $ race                &lt;chr&gt; "White", "White", "White", "White", "White", "Whit…
## $ liberal             &lt;lgl&gt; FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FAL…
## $ party               &lt;chr&gt; "Democrat", "Republican", "Democrat", "Democrat", …
## $ age                 &lt;int&gt; 31, 34, 63, 45, 55, 37, 53, 36, 54, 42, 33, 50, 24…
## $ income              &lt;dbl&gt; 135000, 105000, 135000, 300000, 135000, 87500, 875…
## $ line                &lt;chr&gt; "Framingham", "Framingham", "Framingham", "Framing…
## $ station             &lt;chr&gt; "Grafton", "Southborough", "Grafton", "Grafton", "…
## $ hisp_perc           &lt;dbl&gt; 0.026, 0.015, 0.019, 0.019, 0.019, 0.023, 0.030, 0…
## $ ideology_start      &lt;int&gt; 3, 4, 1, 4, 2, 5, 5, 4, 4, 4, 3, 5, 4, 1, 2, 2, 3,…
## $ ideology_end        &lt;int&gt; 3, 4, 2, 4, 2, 5, 5, 4, 3, 4, 3, 4, 4, 1, 2, 3, 3,…
## $ income_in_thousands &lt;dbl&gt; 135, 105, 135, 300, 135, 88, 88, 135, 105, 135, 10…</code></pre>
<p>The data include information about each respondent’s gender, political affiliations, age, income and so on. <code>treatment</code> indicates whether a subject was in the control or treatment group. The key outcomes are their attitudes toward immigration both before (<code>att_start</code>) and after (<code>att_end</code>) the experiment. We also have a measure of their ideology before and after the experiment, but there is little change. Type <code><a href="https://rdrr.io/pkg/primer.data/man/trains.html">?trains</a></code> to read the help page for more information about each variable. Let’s restrict attention to a subset of the variables.</p>
<!-- Tie above paragraph to selecting data that is relevant to the research question. Think about increasing levels of sophistication in dealing with the "population" question, and discussing examples of what can go wrong. -->
<div class="sourceCode" id="cb746"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ch8</span> <span class="op">&lt;-</span> <span class="va">trains</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">age</span>, <span class="va">att_end</span>, <span class="va">party</span>, <span class="va">income</span>, <span class="va">treatment</span>, <span class="va">liberal</span><span class="op">)</span></code></pre></div>
<p>It is always smart to look at a some random samples of the data:</p>
<div class="sourceCode" id="cb747"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ch8</span> <span class="op">%&gt;%</span> 
  <span class="fu">slice_sample</span><span class="op">(</span>n <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 6
##     age att_end party      income treatment liberal
##   &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt; &lt;fct&gt;     &lt;lgl&gt;  
## 1    55      12 Republican 250000 Control   FALSE  
## 2    46       8 Democrat   250000 Control   FALSE  
## 3    41       5 Democrat   135000 Control   TRUE   
## 4    29       8 Democrat   250000 Control   TRUE   
## 5    41       7 Democrat   250000 Control   FALSE</code></pre>
<p><code>att_end</code> is a measure of person’s attitude toward immigration. A higher number means more conservative, i.e., a more exclusionary stance toward immigration into the United States.</p>
<div class="sourceCode" id="cb749"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ch8</span> <span class="op">%&gt;%</span> 
  <span class="fu">glimpse</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 115
## Columns: 6
## $ age       &lt;int&gt; 31, 34, 63, 45, 55, 37, 53, 36, 54, 42, 33, 50, 24, 40, 53, …
## $ att_end   &lt;dbl&gt; 11, 10, 5, 11, 5, 13, 13, 11, 12, 10, 9, 9, 13, 7, 8, 13, 8,…
## $ party     &lt;chr&gt; "Democrat", "Republican", "Democrat", "Democrat", "Democrat"…
## $ income    &lt;dbl&gt; 135000, 105000, 135000, 300000, 135000, 87500, 87500, 135000…
## $ treatment &lt;fct&gt; Treated, Treated, Treated, Treated, Control, Treated, Contro…
## $ liberal   &lt;lgl&gt; FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE,…</code></pre>
<p>Pay attention to the variable types. Do they make sense? Perhaps. But there are certainly grounds for suspicion. Why is <code>att_end</code> a double rather than an integer? All the values in the data appear to be integers, so there is no benefit to having these variables be doubles. Why is <code>party</code> a character variable and <code>treatment</code> a factor variable? It could be that these are intentional choices made by the creator of the tibble, i.e., us. Or, these could be mistakes. Most likely, these choices are a mixture of sensible and arbitrary. Regardless, it is your responsibility to notice them. You can’t make a good model without looking closely at the data which you are using.</p>
<div class="sourceCode" id="cb751"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ch8</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:unnamed-chunk-577">TABLE 8.1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">115</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">6</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">factor</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">logical</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table></div>
<p><strong>Variable type: character</strong></p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">party</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">8</td>
<td align="right">10</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr></tbody>
</table></div>
<p><strong>Variable type: factor</strong></p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="left">ordered</th>
<th align="right">n_unique</th>
<th align="left">top_counts</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">treatment</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">2</td>
<td align="left">Con: 64, Tre: 51</td>
</tr></tbody>
</table></div>
<p><strong>Variable type: logical</strong></p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="left">count</th>
</tr></thead>
<tbody><tr class="odd">
<td align="left">liberal</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.44</td>
<td align="left">FAL: 64, TRU: 51</td>
</tr></tbody>
</table></div>
<p><strong>Variable type: numeric</strong></p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4.2e+01</td>
<td align="right">12.2</td>
<td align="right">20</td>
<td align="right">33</td>
<td align="right">43</td>
<td align="right">52</td>
<td align="right">68</td>
<td align="left">▆▇▇▇▃</td>
</tr>
<tr class="even">
<td align="left">att_end</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">9.1e+00</td>
<td align="right">2.9</td>
<td align="right">3</td>
<td align="right">7</td>
<td align="right">9</td>
<td align="right">11</td>
<td align="right">15</td>
<td align="left">▂▃▇▃▃</td>
</tr>
<tr class="odd">
<td align="left">income</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1.4e+05</td>
<td align="right">74476.6</td>
<td align="right">23500</td>
<td align="right">87500</td>
<td align="right">135000</td>
<td align="right">135000</td>
<td align="right">300000</td>
<td align="left">▅▇▇▁▆</td>
</tr>
</tbody>
</table></div>
<p><code><a href="https://docs.ropensci.org/skimr/reference/skim.html">skim()</a></code> shows us what the different values of <code>treatment</code> are because it is a factor. Unfortunately, it does not do the same for character variables like <code>party</code>. The ranges for <code>age</code> and <code>att_end</code> seem reasonable. Recall that participants were asked three questions about immigration issues, each of which allowed for an answer indicated strength of agreement on a scale form 1 to 5, with higher values indicating more agreement with conservative viewpoints. <code>att_end</code> is the sum of the responses to the three questions, so the most liberal possible value is 3 and the most conservative is 15.</p>
<p>Always plot your data.</p>
<div class="sourceCode" id="cb752"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ch8</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">party</span>, y <span class="op">=</span> <span class="va">age</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_jitter</span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.1</span>, height <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Age by Party Affiliation in Trains Dataset"</span>,
       subtitle <span class="op">=</span> <span class="st">"Where are the old Republicans?"</span>,
       x <span class="op">=</span> <span class="st">"Party"</span>,
       y <span class="op">=</span> <span class="st">"Age"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-578-1.png" width="100%"></div>
<p>There are more Democrats in this dataset than Republicans. Democrats also span a wider range of ages than Republicans.</p>
<!-- DK: Could do more here. -->
<p>The data that we have are very limited. There are only 115 observations, all from 2012 and involving train commuters to Boston. How useful will this data be today, or for other populations around Boston, or for other cities in the US? Only your judgment, along with advice from your colleagues, can guide you.</p>
<p>The key concept is the idea of a “population.” From which larger population is the data we have being (conceptually) drawn? If we were only interested in the age of individuals in our data set, we would have no need for inference. <em>We know everyone’s ages already.</em> We only need tools like <code><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm()</a></code> if we seek to understand individuals not in our data. Only if our data is “representative,” at least to some extent, of that larger population can we use our data to answer our questions.</p>
<!-- Relate back to research questions and the population for them -->
<!-- Discuss whether the data comes from the same population as preceptor table -->
<!-- This sections ends with the Population  Table. -->
</div>
</div>
<div id="justice-2" class="section level3" number="8.2.2">
<h3>
<span class="header-section-number">8.2.2</span> Justice<a class="anchor" aria-label="anchor" href="#justice-2"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-579"></span>
<img src="other/images/Justice.jpg" alt="Justice" width="100%"><p class="caption">
FIGURE 8.2: Justice
</p>
</div>
<p>Justice, in data science, consists of three topics: predictive versus causal modeling, the Preceptor Table, and a mathematical formulation of the model.</p>
<!-- Ch.5 states key aspects are representativeness, validity, and data generating mechanism. Correct! This is all garbage! -->
<p>Any model with age as its dependent variable will be predictive, not causal, for the simple reason that nothing, other than time, can change your age. You are X years old. It would not matter if you changed your party registration from Democrat to Republican or vice versa. Your age is your age.</p>
<p>There is only one potential outcome, i.e., one outcome. There is not a potential outcome if you are Democrat and a different potential outcome if you are a Republican.</p>
<p>When dealing with a non-causal model, the focus is on predicting things. The underlying mechanism which connects age with party is less important than the brute statistical fact that there is a connection. <em>Predictive models care little about causality.</em></p>
<!-- DK: Preceptor Tables should be laid out like the formula: outcome on left, predictors on right. -->
<!-- DK: Need a table which shows all 4 (?) languages for describing a model together: English, math, code, output. -->
<p>A good way at looking at this is with a Preceptor Table, as seen below. Unlike the previous table in Chapter <a href="two-parameters.html#two-parameters">7</a>, we now have two columns in addition to ID. Since our data does not include all Republicans and Democrats in the world, not every row is filled in.</p>
<div id="bgzaxdtyuk" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#bgzaxdtyuk .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#bgzaxdtyuk .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bgzaxdtyuk .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#bgzaxdtyuk .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#bgzaxdtyuk .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bgzaxdtyuk .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#bgzaxdtyuk .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#bgzaxdtyuk .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#bgzaxdtyuk .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#bgzaxdtyuk .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#bgzaxdtyuk .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#bgzaxdtyuk .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#bgzaxdtyuk .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#bgzaxdtyuk .gt_from_md > :first-child {
  margin-top: 0;
}

#bgzaxdtyuk .gt_from_md > :last-child {
  margin-bottom: 0;
}

#bgzaxdtyuk .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#bgzaxdtyuk .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#bgzaxdtyuk .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bgzaxdtyuk .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#bgzaxdtyuk .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#bgzaxdtyuk .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#bgzaxdtyuk .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#bgzaxdtyuk .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#bgzaxdtyuk .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bgzaxdtyuk .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#bgzaxdtyuk .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#bgzaxdtyuk .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#bgzaxdtyuk .gt_left {
  text-align: left;
}

#bgzaxdtyuk .gt_center {
  text-align: center;
}

#bgzaxdtyuk .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#bgzaxdtyuk .gt_font_normal {
  font-weight: normal;
}

#bgzaxdtyuk .gt_font_bold {
  font-weight: bold;
}

#bgzaxdtyuk .gt_font_italic {
  font-style: italic;
}

#bgzaxdtyuk .gt_super {
  font-size: 65%;
}

#bgzaxdtyuk .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<div class="inline-table"><table class="gt_table">
<thead class="gt_col_headings">
<tr>
<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" style="text-align: left; vertical-align: middle;">ID</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="1">
        <span class="gt_column_spanner">Predictor</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="1">
        <span class="gt_column_spanner">Outcome</span>
      </th>
    </tr>
<tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Political Party</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">Age</th>
    </tr>
</thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">1</td>
<td class="gt_row gt_center">D</td>
<td class="gt_row gt_center">31</td>
</tr>
<tr>
<td class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">2</td>
<td class="gt_row gt_center">?</td>
<td class="gt_row gt_center">?</td>
</tr>
<tr>
<td class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">...</td>
<td class="gt_row gt_center">...</td>
<td class="gt_row gt_center">...</td>
</tr>
<tr>
<td class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">473</td>
<td class="gt_row gt_center">D</td>
<td class="gt_row gt_center">58</td>
</tr>
<tr>
<td class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">474</td>
<td class="gt_row gt_center">?</td>
<td class="gt_row gt_center">?</td>
</tr>
<tr>
<td class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">...</td>
<td class="gt_row gt_center">...</td>
<td class="gt_row gt_center">...</td>
</tr>
<tr>
<td class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">3,258</td>
<td class="gt_row gt_center">?</td>
<td class="gt_row gt_center">?</td>
</tr>
<tr>
<td class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">3,259</td>
<td class="gt_row gt_center">R</td>
<td class="gt_row gt_center">49</td>
</tr>
<tr>
<td class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">...</td>
<td class="gt_row gt_center">...</td>
<td class="gt_row gt_center">...</td>
</tr>
<tr>
<td class="gt_row gt_left" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">N</td>
<td class="gt_row gt_center">?</td>
<td class="gt_row gt_center">?</td>
</tr>
</tbody>
</table></div>
</div>
<p> </p>
<p>We now know that we are working with a predictive model. Recall:</p>
<p><span class="math display">\[\text{outcome} = \text{model} + \text{not in the model}\]</span></p>
<p>In words, any event depends on our explicitly described model as well as on influences unknown to us. Everything that happens in the world is the result of various factors, and we can only consider some of them in our model (because we do not know about some influences, or because we have no data about them).</p>
<p>The mathematics:</p>
<!-- DK: Should standardize the notation across the book. -->
<p><span class="math display">\[ y_i = \beta_1 republican_i + \beta_2 democrat_i + \epsilon_i\]</span></p>
<p>where 
<span class="math display">\[republican_i, democrat_i \in \{0,1\}\]</span> 
<span class="math display">\[republican_i +  democrat_i = 1\]</span> 
<span class="math display">\[\epsilon_i \sim N(0, \sigma^2)\]</span></p>
<p>Don’t panic dear poets and philosophers, the whole thing is easier than it looks.</p>
<!-- DK: This whole section is very awkward. Start with which is data and which is parameters. 
     MM: Agree, found some parts of this a little difficult to follow -->
<ul>
<li><p>On the left-hand side we have the outcome, <span class="math inline">\(y_i\)</span>, which is the variable to be explained. In our case, this is the age of an individual in the population.</p></li>
<li><p>On the right-hand side we first have the part contained in the model: two similar terms added together. Each term consists of a parameter and a data point. The betas are our two parameters: <span class="math inline">\(\beta_1\)</span> is the average age of Republicans in the population and <span class="math inline">\(\beta_2\)</span> is the average age of Democrats in the population. <span class="math inline">\(republican_i\)</span> and <span class="math inline">\(democrat_i\)</span> are our explanatory variables and take the values 1 or 0. If person <span class="math inline">\(i\)</span> is a Republican we have <span class="math inline">\(republican_i = 1\)</span> and <span class="math inline">\(democrat_i = 0\)</span>. If person <span class="math inline">\(i\)</span> is a Democrat we have <span class="math inline">\(republican_i = 0\)</span> and <span class="math inline">\(democrat_i = 1\)</span>. In other words, their values are mutually exclusive – if you are a Democrat, you cannot also be a Republican.</p></li>
</ul>
<!-- DK: "Connected to" is awkward here. --><ul>
<li><p>The last part, <span class="math inline">\(\epsilon_i\)</span> (“epsilon”), represents the unexplained part of the outcome and is called the error term. It is simply the difference between the outcome and our model predictions. This includes all factors that have an influence on someone’s age but are not connected to party affiliation. We assume that this error follows a normal distribution with an expected value of 0 (meaning it is 0 on average).</p></li>
<li><p>The small <span class="math inline">\(i\)</span>’s are an index to number the observations. It is equivalent to the “ID” column in our Preceptor Table and simply states that the outcome for person <span class="math inline">\(i\)</span> is explained by the modeled and non-modeled factors for person <span class="math inline">\(i\)</span>.</p></li>
<li><p>The model is a claim about how the world works, not just for the 115 individuals for which we have data but for the all the people in the population for which we seek to draw inferences.</p></li>
<li><p>Although terminology differs across academic fields, the most common term to describe a model like this is a “regression.” We are “regressing” <code>age</code> on <code>party</code> in order to see if they are associated with each other. The formula above is a “regression formula,” and the model is a “regression model.” This terminology would also apply to our model of <code>height</code> in Chapter <a href="two-parameters.html#two-parameters">7</a>.</p></li>
<li><p>The model in Chapter <a href="two-parameters.html#two-parameters">7</a> is sometimes called “intercept-only” because the only (interesting) parameter is the intercept. Here we have a “two intercept” model because, instead of estimating an average for the whole population, we are estimating two averages.</p></li>
</ul>
<!-- MM: Reinforce representativeness and validity of the data -->
</div>
<div id="courage-2" class="section level3" number="8.2.3">
<h3>
<span class="header-section-number">8.2.3</span> Courage<a class="anchor" aria-label="anchor" href="#courage-2"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-581"></span>
<img src="other/images/Courage.jpg" alt="Courage" width="100%"><p class="caption">
FIGURE 8.3: Courage
</p>
</div>
<p>Courage allows us to translate math to code.</p>
<p>To get posterior distributions for our three parameters, we will again use <code><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm()</a></code>, just as we did in Chapter <a href="two-parameters.html#two-parameters">7</a>.</p>
<div class="sourceCode" id="cb753"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit_1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">age</span> <span class="op">~</span> <span class="va">party</span> <span class="op">-</span> <span class="fl">1</span>, 
                    data <span class="op">=</span> <span class="va">trains</span>, 
                    seed <span class="op">=</span> <span class="fl">17</span>,
                    refresh <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></code></pre></div>
<ul>
<li><p>The variable before the tilde, <code>age</code>, is our outcome.</p></li>
<li><p>The only explanatory variable is <code>party</code>. This variable has only two values, ‘Democrat’ and ‘Republican.’</p></li>
<li><p>We have also added <code>-1</code> at the end of the equation, indicating that we do not want an intercept, which would otherwise be added by default.</p></li>
</ul>
<p>The resulting output:</p>
<div class="sourceCode" id="cb754"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit_1</span></code></pre></div>
<pre><code>## stan_glm
##  family:       gaussian [identity]
##  formula:      age ~ party - 1
##  observations: 115
##  predictors:   2
## ------
##                 Median MAD_SD
## partyDemocrat   42.6    1.2  
## partyRepublican 41.2    2.7  
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 12.3    0.8  
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p><code>partyDemocrat</code> corresponds to <span class="math inline">\(\beta_1\)</span>, the average age of Democrats in the population. <code>partyRepublican</code> corresponds to <span class="math inline">\(\beta_2\)</span>, the average age of Republicans in the population. Since we don’t really care about the posterior distribution for <span class="math inline">\(\sigma\)</span>, we won’t discuss it here. Graphically:</p>
<!-- DK: Lots to clean up about this plot! -->
<!-- DK: Should we use different parameter names like beta_r? -->
<div class="sourceCode" id="cb756"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit_1</span> <span class="op">%&gt;%</span> 
  <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">sigma</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>Democrat <span class="op">=</span> <span class="va">partyDemocrat</span>, Republican <span class="op">=</span> <span class="va">partyRepublican</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">pivot_longer</span><span class="op">(</span>cols <span class="op">=</span> <span class="va">Democrat</span><span class="op">:</span><span class="va">Republican</span>,
               names_to <span class="op">=</span> <span class="st">"parameter"</span>,
               values_to <span class="op">=</span> <span class="st">"age"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, fill <span class="op">=</span> <span class="va">parameter</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">count</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
                   alpha <span class="op">=</span> <span class="fl">0.5</span>, 
                   bins <span class="op">=</span> <span class="fl">100</span>, 
                   position <span class="op">=</span> <span class="st">"identity"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Posterior for Average Age"</span>,
         subtitle <span class="op">=</span> <span class="st">"More data allows for a more precise posterior for Democrats"</span>,
         x <span class="op">=</span> <span class="st">"Age"</span>,
         y <span class="op">=</span> <span class="st">"Probability"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-584-1.png" width="100%"></div>
<p>The unknown parameters <span class="math inline">\(\beta_1\)</span> (partyDemocrat) and <span class="math inline">\(\beta_2\)</span> (partyRepublican) are still unknown. We can never know the true average age of all Democrats in the population. But we can calculate a posterior probability distribution for each parameter. Comments:</p>
<ul>
<li><p>Democrats seem slightly older than Republicans. That was true in the sample and so, almost (but not quite!) by definition, it will be true in our the posterior probability distributions.</p></li>
<li><p>Our estimate for the average age of Democrats in the population is much more precise than that for Republicans because we have five times as many Democrats as Republicans in our sample. A central lesson from Chapter <a href="one-parameter.html#one-parameter">6</a> is that the more data you have related to a parameter, the narrower your posterior distribution will be.</p></li>
<li><p>There is a great deal of overlap between the two distributions. Would we be surprised if, in truth, the average age of Republicans in the population was greater than that for Democrats? Not really. We don’t have enough data to be sure either way.</p></li>
<li><p>The phrase “in the population” is doing a great deal of work because we have not said what, precisely, we mean by the “population.” Is it the set of people on those commuter platforms on those days in 2012 when the experiment was done? Is it the set of people on all platforms, including ones never visited? Is it the set of all Boston commuter? All Massachusetts residents? All US residents? Does it include people today, or can we only draw inferences for 2012? We will explore these questions in every model we create.</p></li>
</ul>
<!-- MM: touched on in the wisdom section in ch. 5, as well as justice in terms of representativeness does it belong there? --><ul>
<li>The parameters <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> can be interpreted in two ways. First, like all parameters, they are a part of the model. We need to estimate them. But, in many cases, we don’t really care what the value of the parameter is. The exact value of <span class="math inline">\(\sigma\)</span>, for example, does not really matter. Second, some parameters have a substantive interpretaion, as with <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> being the average ages in the population. But this will often not be the case! Fortunately, with such models, we can use functions like <code><a href="https://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html">posterior_epred()</a></code> and <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code> to answer our questions.</li>
</ul>
<p>Consider a table which shows a sample of 8 individuals.</p>
<div id="ivfeevngci" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ivfeevngci .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ivfeevngci .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ivfeevngci .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ivfeevngci .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ivfeevngci .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ivfeevngci .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ivfeevngci .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ivfeevngci .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ivfeevngci .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ivfeevngci .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ivfeevngci .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ivfeevngci .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ivfeevngci .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ivfeevngci .gt_from_md > :first-child {
  margin-top: 0;
}

#ivfeevngci .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ivfeevngci .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ivfeevngci .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#ivfeevngci .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ivfeevngci .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#ivfeevngci .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ivfeevngci .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ivfeevngci .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ivfeevngci .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ivfeevngci .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ivfeevngci .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#ivfeevngci .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ivfeevngci .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#ivfeevngci .gt_left {
  text-align: left;
}

#ivfeevngci .gt_center {
  text-align: center;
}

#ivfeevngci .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ivfeevngci .gt_font_normal {
  font-weight: normal;
}

#ivfeevngci .gt_font_bold {
  font-weight: bold;
}

#ivfeevngci .gt_font_italic {
  font-style: italic;
}

#ivfeevngci .gt_super {
  font-size: 65%;
}

#ivfeevngci .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<div class="inline-table"><table class="gt_table">
<thead class="gt_header"><tr>
<th colspan="4" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>8 Observations from Trains Dataset</th>
    </tr></thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Age</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Party</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Fitted</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Residual</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center">31</td>
<td class="gt_row gt_center">Democrat</td>
<td class="gt_row gt_center">42.59</td>
<td class="gt_row gt_center">-11.6</td>
</tr>
<tr>
<td class="gt_row gt_center">34</td>
<td class="gt_row gt_center">Republican</td>
<td class="gt_row gt_center">41.19</td>
<td class="gt_row gt_center">-7.2</td>
</tr>
<tr>
<td class="gt_row gt_center">63</td>
<td class="gt_row gt_center">Democrat</td>
<td class="gt_row gt_center">42.59</td>
<td class="gt_row gt_center">20.4</td>
</tr>
<tr>
<td class="gt_row gt_center">45</td>
<td class="gt_row gt_center">Democrat</td>
<td class="gt_row gt_center">42.59</td>
<td class="gt_row gt_center">2.4</td>
</tr>
<tr>
<td class="gt_row gt_center">55</td>
<td class="gt_row gt_center">Democrat</td>
<td class="gt_row gt_center">42.59</td>
<td class="gt_row gt_center">12.4</td>
</tr>
<tr>
<td class="gt_row gt_center">37</td>
<td class="gt_row gt_center">Democrat</td>
<td class="gt_row gt_center">42.59</td>
<td class="gt_row gt_center">-5.6</td>
</tr>
<tr>
<td class="gt_row gt_center">53</td>
<td class="gt_row gt_center">Republican</td>
<td class="gt_row gt_center">41.19</td>
<td class="gt_row gt_center">11.8</td>
</tr>
<tr>
<td class="gt_row gt_center">36</td>
<td class="gt_row gt_center">Democrat</td>
<td class="gt_row gt_center">42.59</td>
<td class="gt_row gt_center">-6.6</td>
</tr>
</tbody>
</table></div>
</div>
<!-- DK: More extreme awkwardness. -->
<p> </p>
<p>The fitted values are the same for all Republicans and for all Democrats, as the model produces one fitted value for each condition. This table shows how just a sample of 8 individuals captures a wide range of residuals, making it difficult to predict the age of a new individual. We can get a better picture of the unmodeled variation in our sample if we plot these three variables for all the individuals in our data.</p>
<p>The following three histograms show the actual outcomes, fitted values, and residuals of all people in <code>trains</code>:</p>
<!-- DK: Clean up these plots to be similar across chapters! Also, we should ensure that the width of 10 units is the same in each plot. Or does that already happen? Want the intuition that, the more predictive the model, the smaller the remaining variation in the residuals. The below is from chapter 7. -->
<div class="sourceCode" id="cb757"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">outcome</span> <span class="op">&lt;-</span> <span class="va">ch8</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Age"</span>,
         y <span class="op">=</span> <span class="st">"Count"</span><span class="op">)</span> 

<span class="va">fitted</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/fitted.values.html">fitted</a></span><span class="op">(</span><span class="va">fit_1</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_bar</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Fitted Values"</span>,
         y <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_x_continuous</span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">20</span>, <span class="fl">70</span><span class="op">)</span><span class="op">)</span> 

<span class="va">res</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>resids <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">fit_1</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span><span class="va">resids</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span>bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Residuals"</span>,
         y <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span> 
  

<span class="va">outcome</span> <span class="op">+</span> <span class="va">fitted</span> <span class="op">+</span> <span class="va">res</span> <span class="op">+</span>
  <span class="fu">plot_annotation</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Decomposition of Height into Fitted Values and Residuals"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-586-1.png" width="100%"></div>
<p>The three plots are structured like our equation and table above. A value in the left plot is the sum of one value from the middle plot plus one from the right plot.</p>
<ul>
<li><p>The actual age distribution looks like a normal distribution. It is centered around 43, and it has a standard deviation of about 12 years.</p></li>
<li><p>The middle plot for the fitted values shows only two adjacent spikes, which represent the estimates for Democrats and Republicans.</p></li>
<li><p>Since the residuals plot represents the difference between the other two plots, its distribution looks like the first plot.</p></li>
</ul>
<!-- DK: All unclear and would benefit from clean up. -->
</div>
<div id="temperance-2" class="section level3" number="8.2.4">
<h3>
<span class="header-section-number">8.2.4</span> Temperance<a class="anchor" aria-label="anchor" href="#temperance-2"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-587"></span>
<img src="other/images/Temperance.jpg" alt="Temperance" width="100%"><p class="caption">
FIGURE 8.4: Temperance
</p>
</div>
<p>Recall the first questions with which we began this section:</p>
<ul>
<li>What is the probability that, if a Democrat shows up at the train station, he will be over 50 years old?</li>
</ul>
<p>So far we have only tried our model on people from our data set whose real age we already knew. This is helpful to understand the model, but our ultimate goal is to understand more about the real world, about people we don’t yet know much about. Temperance guides us to make meaningful predictions and to become aware of their known and unknown limitations.</p>
<p>Start with a simple question, what are the chances that a random Democrat is over 50 years old? First, we create a tibble with the desired input for our model. In our case the tibble has a variable named “party” which contains a single observation with the value “Democrat.” This is a bit different than Chapter <a href="two-parameters.html#two-parameters">7</a>.</p>
<div class="sourceCode" id="cb758"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">new_obs</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>party <span class="op">=</span> <span class="st">"Democrat"</span><span class="op">)</span></code></pre></div>
<!-- DK: Does this D_age work? If so, similar discussion should be used more broadly. Also discuss R_age. Even Person_age for a random person, an analysis which accounts for the mix of Rs and Ds in the sample/population. -->
<p>Use <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code> to create draws from the posterior for this scenario. Note that we have a new posterior distribution under consideration here. The unknown parameter, call it <span class="math inline">\(D_{age}\)</span>, is the age of a Democrat. This could be the age of a randomly selected Democrat from the population or of the next Democrat we meet or of the next Democrat we interview on the train platform. The definition of “population” determines the appropriate interpretation. Yet, regardless, <span class="math inline">\(D_{age}\)</span> is an unknown parameter. But it is not one — like <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span>, or <span class="math inline">\(\sigma\)</span> — for which we have already created a posterior probability distribution. That is why we need <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code>.</p>
<p><code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code> takes two arguments: the model for which the simulations should be run, and a tibble indicating for which and how many parameters we want to run these simulations. In this case, the model is the one from Courage and the tibble is the one we just created.</p>
<div class="sourceCode" id="cb759"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict</a></span><span class="op">(</span><span class="va">fit_1</span>, newdata <span class="op">=</span> <span class="va">new_obs</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">mutate_all</span><span class="op">(</span><span class="va">as.numeric</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">pp</span>, <span class="fl">10</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 1
##      `1`
##    &lt;dbl&gt;
##  1  50.8
##  2  50.8
##  3  26.4
##  4  44.8
##  5  35.4
##  6  46.9
##  7  39.0
##  8  49.5
##  9  41.3
## 10  33.1</code></pre>
<p>We might expect that we can use <code>as_tibble()</code> directly after the object returned <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code>. Sadly, for obscure technical reasons, that won’t quite work. So, we need the incantation <code>mutate_all(as.numeric)</code> to make sure that the resulting tibble is well-behaved. This command ensures that every column in the tibble is a simple numeric vector, which is what we want.</p>
<p>The result are draws from the posterior distribution of the age of a Democrat. It is important to understand that this is not a concrete person from the <code>trains</code> dataset - the algorithm in <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code> simply uses the existing data from <code>trains</code> to estimate this posterior distribution.</p>
<div class="sourceCode" id="cb761"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pp</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">`1`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">count</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
                   bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span>  <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Posterior for a Random Democrat's Age"</span>,
         subtitle <span class="op">=</span> <span class="st">"Individual predictions are always more variable than expected values"</span>,
         x <span class="op">=</span> <span class="st">"Age"</span>,
         y <span class="op">=</span> <span class="st">"Probability"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-590-1.png" width="100%"></div>
<p>Once we have the posterior distribution, we can answer (almost) any reasonable question. In this case, the probability that the next Democrat will be over 50 is around 28%.</p>
<div class="sourceCode" id="cb762"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">pp</span><span class="op">$</span><span class="va">`1`</span> <span class="op">&gt;</span> <span class="fl">50</span><span class="op">)</span> <span class="op">/</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">pp</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.27</code></pre>
<p>Recall the second question:</p>
<ul>
<li>In a group of three Democrats and three Republicans, what will the age difference be between the oldest Democrat and the youngest Republican?</li>
</ul>
<p>As before we start by creating a tibble with the desired input. Note that the name of the column (“party”) and the observations (“Democrat,” “Republican”) must always be <em>exactly</em> as they are in the original data set. This tibble as well as our model can then be used as arguments for <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code>:</p>
<div class="sourceCode" id="cb764"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">newobs</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>party <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Democrat"</span>, <span class="st">"Democrat"</span>, <span class="st">"Democrat"</span>, 
                        <span class="st">"Republican"</span>, <span class="st">"Republican"</span>,<span class="st">"Republican"</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict</a></span><span class="op">(</span><span class="va">fit_1</span>, newdata <span class="op">=</span> <span class="va">newobs</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">mutate_all</span><span class="op">(</span><span class="va">as.numeric</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 4,000 x 6
##      `1`   `2`   `3`   `4`   `5`   `6`
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  38.7  59.6  52.6  43.3  48.8  41.5
##  2  34.3  56.0  31.4  45.8  59.5  39.1
##  3  25.4  15.1  28.6  41.8  38.3  43.9
##  4  56.4  27.2  33.8  34.6  60.1  48.2
##  5  63.2  31.6  49.3  43.7  53.5  27.8
##  6  24.6  45.0  57.1  69.3  64.1  53.8
##  7  52.8  35.8  41.3  62.2  60.4  58.0
##  8  42.9  40.6  57.4  38.5  34.7  30.1
##  9  47.7  22.6  32.5  52.9  47.6  35.1
## 10  40.7  25.3  49.7  40.6  42.2  48.2
## # … with 3,990 more rows</code></pre>
<!-- DK: These pp objects are fundamentally flawed because some of the predicted values are absurdly low, even negative! This is not the fault of the model or the code. It is simply that, if sigma is large enough, then the model thinks a negative age is plausible. We should at least mention this, ideally as part of a posterior predictive check, perhaps in a problem set. -->
<p>We have 6 columns: one for each person. <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code> does not name the columns, but they are arranged in the same order in which we specified the persons in <code>newobs</code>: D, D, D, R, R, R. To determine the expected age difference, we add code which works with these posterior draws:</p>
<!-- DK: I am unsure about this code. Would c() in place of c_across() work as well? -->
<!-- DK: This works without mutate(all...), but it takes much more time than it should because the the pp object still has every column as a ppd object, even after as_tibble(). The rest of the code still works, but takes a 100x longer than it should. Maybe that is a better approach for handling the ppd problem? Just ignore it and take the time hit? -->
<div class="sourceCode" id="cb766"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict</a></span><span class="op">(</span><span class="va">fit_1</span>, newdata <span class="op">=</span> <span class="va">newobs</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">mutate_all</span><span class="op">(</span><span class="va">as.numeric</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  
    <span class="co"># We don't need to rename the columns, but doing so makes the subsequest</span>
    <span class="co"># code much easier to understand. We could just have worked with columns 1,</span>
    <span class="co"># 2, 3 and so on. Either way, the key is to ensure that you correctly map</span>
    <span class="co"># the covariates in newobs to the columns in the posterior_predict object.</span>
  
    <span class="fu">set_names</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"dem_1"</span>, <span class="st">"dem_2"</span>, <span class="st">"dem_3"</span>, 
                <span class="st">"rep_1"</span>, <span class="st">"rep_2"</span>, <span class="st">"rep_3"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
    <span class="fu">rowwise</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  
  <span class="co"># Creating three new columns. The first two are the highest age among</span>
  <span class="co"># Democrats and the lowest age among Republicans, respectively. The third one</span>
  <span class="co"># is the difference between the first two.</span>
  
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>dems_oldest <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="fu">c_across</span><span class="op">(</span><span class="va">dem_1</span><span class="op">:</span><span class="va">dem_3</span><span class="op">)</span><span class="op">)</span>,
         reps_youngest <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="fu">c_across</span><span class="op">(</span><span class="va">rep_1</span><span class="op">:</span><span class="va">rep_3</span><span class="op">)</span><span class="op">)</span>,
         age_diff <span class="op">=</span> <span class="va">dems_oldest</span> <span class="op">-</span> <span class="va">reps_youngest</span><span class="op">)</span>

<span class="va">pp</span></code></pre></div>
<pre><code>## # A tibble: 4,000 x 9
## # Rowwise: 
##    dem_1 dem_2 dem_3 rep_1 rep_2 rep_3 dems_oldest reps_youngest age_diff
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;
##  1  44.6  39.6  50.9  62.1  33.2  36.4        50.9          33.2    17.6 
##  2  55.1  42.5  43.1  33.9  30.4  49.5        55.1          30.4    24.6 
##  3  16.0  34.2  30.4  60.5  41.2  55.0        34.2          41.2    -7.03
##  4  31.9  34.6  43.5  57.7  28.3  49.5        43.5          28.3    15.2 
##  5  50.5  48.8  31.5  43.7  44.7  24.9        50.5          24.9    25.6 
##  6  26.6  35.1  39.2  53.5  32.4  33.0        39.2          32.4     6.79
##  7  47.4  32.7  54.8  44.6  12.0  30.4        54.8          12.0    42.8 
##  8  48.4  30.9  42.1  35.4  36.2  50.0        48.4          35.4    13.0 
##  9  55.8  52.3  40.0  55.3  30.3  37.1        55.8          30.3    25.5 
## 10  55.3  52.3  26.4  58.2  46.7  40.4        55.3          40.4    14.8 
## # … with 3,990 more rows</code></pre>
<p>The plotting code is similar to what we have seen before:</p>
<div class="sourceCode" id="cb768"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pp</span> <span class="op">%&gt;%</span>  
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">age_diff</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">count</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
                   bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Posterior for Age Difference"</span>,
         subtitle <span class="op">=</span> <span class="st">"Oldest of three Democrats compared to youngest of three Republicans"</span>,
         x <span class="op">=</span> <span class="st">"Age"</span>,
         y <span class="op">=</span> <span class="st">"Probability"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-594-1.png" width="100%"></div>
<p>In words, we would expect the oldest Democrat to be about 22 years older than the youngest Republican, but we would not be too surprised if the oldest Democrat was actually younger than the youngest Republican in a group of 6.</p>
</div>
<div id="addendum" class="section level3" number="8.2.5">
<h3>
<span class="header-section-number">8.2.5</span> Addendum<a class="anchor" aria-label="anchor" href="#addendum"><i class="fas fa-link"></i></a>
</h3>
<p>Instead of parameterizing this model without an intercept, we could have used one. In that case, the math would be:</p>
<p><span class="math display">\[ y_i = \beta_0  + \beta_1 democratic_i + \epsilon_i\]</span>
The interpretations of the parameters are different from the prior model. <span class="math inline">\(\beta_0\)</span> is now the average age of Republicans. This is the same interpretation as <span class="math inline">\(\beta_1\)</span> in the original set up. <span class="math inline">\(\beta_1\)</span> is now the difference between the the average age of Republicans and that of Democrats.</p>
<p>To fit this model, we use the exact same code as before, except without the <code>-1</code> in the <code>formula</code> argument.</p>
<div class="sourceCode" id="cb769"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">age</span> <span class="op">~</span> <span class="va">party</span>, 
         data <span class="op">=</span> <span class="va">trains</span>, 
         seed <span class="op">=</span> <span class="fl">98</span>,
         refresh <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></code></pre></div>
<pre><code>## stan_glm
##  family:       gaussian [identity]
##  formula:      age ~ party
##  observations: 115
##  predictors:   2
## ------
##                 Median MAD_SD
## (Intercept)     42.6    1.3  
## partyRepublican -1.5    3.1  
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 12.3    0.8  
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p>The intercept, 42.6, is the same as the <code>partyDemocrat</code> estimate in the first model. The <code>partyRepublican</code> estimate, which was previously 41.0, is now -1.5, meaning it is the difference (allowing for rounding) between the average age of Democrats and Republicans.</p>
<p>Little else about the models will be different. They will have the same fitted values and residuals. <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code> will generate the same posterior predictive probabilty distributions. Which parameterization we use does not matter much. But you should be able to interpret the meaning of the coefficients in both.</p>
<!-- DK: Need more here? -->
</div>
</div>
<div id="att_end-treatment" class="section level2" number="8.3">
<h2>
<span class="header-section-number">8.3</span> att_end ~ treatment<a class="anchor" aria-label="anchor" href="#att_end-treatment"><i class="fas fa-link"></i></a>
</h2>
<p>Above, we created a predictive model: with someone’s party affiliation, we can make a better guess as to what their age is than we could have in the absence of information about their party. There was nothing causal about that model. Changing someone’s party registration can not change their age. In this example, we build a causal model. Consider these two questions:</p>
<p><em>What is the average treatment effect, of exposing people to Spanish-speakers, on their attitudes toward immigration?</em></p>
<p><em>What is the largest causal effect which still has a 1 in 10 chance of occurring?</em></p>
<p>Models help us answer questions better than we could without those models, but only if we follow the Cardinal Virtues.</p>
<div id="wisdom-4" class="section level3" number="8.3.1">
<h3>
<span class="header-section-number">8.3.1</span> Wisdom<a class="anchor" aria-label="anchor" href="#wisdom-4"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-596"></span>
<img src="other/images/Wisdom.jpg" alt="Wisdom" width="100%"><p class="caption">
FIGURE 8.5: Wisdom
</p>
</div>
<!-- MM: ideal preceptor table, what kind of data would we need, then look at data? -->
<p><em>Look at your data!</em> Before making a model which seeks to explain <code>att_end</code>, we should plot <code>att_end</code> and the variable we think is connected to it.</p>
<div class="sourceCode" id="cb771"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ch8</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">treatment</span>, y <span class="op">=</span> <span class="va">att_end</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_jitter</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Attitude End and Treatment in Enos (2014)"</span>,
       subtitle <span class="op">=</span> <span class="st">"Did the treatment make people more conservative?"</span>,
       x <span class="op">=</span> <span class="st">"Treatment"</span>,
       y <span class="op">=</span> <span class="st">"Attitude After Experiment"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-597-1.png" width="100%"></div>
<p>Treated individuals seem to have a higher values for <code>att_end</code> than control individuals, although there is a great deal of variation in both.</p>
<!-- DK: Could do more here. -->
<p>We are still using the data from <span class="citation"><a href="references.html#ref-enos2014" role="doc-biblioref">Enos</a> (<a href="references.html#ref-enos2014" role="doc-biblioref">2014</a>)</span>. Yet the world is a very different place today! Is data from 2012, four years before Donald Trump’s election as president, still relevant? Can we generalize data from Boston commuters to other people in Massachusetts, to other people in the US? There are no obvious answers to these questions. <em>The data we have is never a perfect match to the problem we face because data is always old.</em> The world is constantly changing. To use old data, we need to make assumptions about the stability of our model of the world and of the parameters we are estimating. Whether those assumptions are reasonable is a difficult question, one that requires knowledge about the world as it was and the world as it now is. <em>Math won’t save us.</em></p>
<p>The issue is always: Do the data we have and the data we want to have come from the same population? If there is no connection between the two, progress is impossible. But, in this case, if we are willing to consider the population to be US residents over the last decade (including today), and if we are willing to assume that our data set of 115 individuals is representative of that population, then we can use our data to create a model to answer our question.</p>
<p>Ethical issues are tricky, or at least trickier than they were in the context of models in which the dependent variable was height or age. (And the ethical issues in conducting the experiment in the first place are non-trivial.) Assume we make a good model. What is to prevent someone from using that information to, say, influence voting and donations? Imagine a Republican Senate candidate who hires Spanish-speakers to ride commuter trains in order to shift voters’ attitudes toward immigration in a conservative direction. She believes (correctly?) that doing so will increase her odds of winning the election. Is that the sort of knowledge we seek to create? We can make such models. Indeed, the purpose of this chapter is to show you how to do so! But should you make those models?</p>
</div>
<div id="justice-3" class="section level3" number="8.3.2">
<h3>
<span class="header-section-number">8.3.2</span> Justice<a class="anchor" aria-label="anchor" href="#justice-3"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-598"></span>
<img src="other/images/Justice.jpg" alt="Justice" width="100%"><p class="caption">
FIGURE 8.6: Justice
</p>
</div>
<p>The two elements of Justice in a data science project remain the same: the Preceptor Table and the mathematical formula.</p>
<!-- MM: should be three elements: representativeness, validity, and formula -->
<p>A Preceptor Table for this model would look very similar to the one in the first half of this chapter, except that we have now possible outcomes for each individual: <code>att_end</code> if they are exposed to treatment and <code>att_end</code> if they are exposed to control.</p>
<!-- DK: We need to add Preceptor Tables here and elsewhere. The below one is wrong because it does not show two potential outcomes.  Should use proper potential outcome notation, as introduced in chapter 4. -->
<!-- MM: Agree: Preceptor tables need to be added here as well as in wisdom -->
<p>The math for this model is exactly the same as the math for the predictive model in the first part of this chapter, although we change the notation a bit for clarity.</p>
<p><span class="math display">\[ y_i = \beta_1 treatment_i + \beta_2 control_i + \epsilon_i\]</span></p>
<p>where 
<span class="math display">\[treatment_i, control_i \in \{0,1\}\]</span> 
<span class="math display">\[treatment_i +  control_i = 1\]</span> 
<span class="math display">\[\epsilon_i \sim N(0, \sigma^2)\]</span></p>
<!-- DK: make these sections much more similar across the chapters, always separating out the data and the paramters -->
<p>Nothing has changed, except for the meaning of the data items and the interpretations of the parameters.</p>
<!-- MM: Possibly directly compare to add clarity to how meaning/interpretations change -->
<ul>
<li><p>On the left-hand side we have the outcome, <span class="math inline">\(y_i\)</span>, which is the variable to be explained. In our case, this is a person’s attitude toward immigration after the experiment is complete. <span class="math inline">\(y_i\)</span> takes on integer values between 3 and 15 inclusive.</p></li>
<li><p>On the right-hand side we first have the part contained in the model, consisting of two similar terms. The two terms stand for Treated and Control and work as follows. Each term consists of a parameter and a data point. <span class="math inline">\(\beta_1\)</span> is the average attitude toward immigration for treated individuals — those exposed to Spanish-speakers — in the population. <span class="math inline">\(\beta_2\)</span> is the average attitude toward immigration for control individuals — those not exposed to Spanish-speakers — in the population. The <span class="math inline">\(x\)</span>’s are our explanatory variables and take the values 1 or 0. If person <span class="math inline">\(i\)</span> is Treated, <span class="math inline">\(treatment_i = 1\)</span> and <span class="math inline">\(control_i = 0\)</span>. If person <span class="math inline">\(i\)</span> is Control, <span class="math inline">\(treatment_i = 0\)</span> and <span class="math inline">\(control_i = 1\)</span>. In other words, these are binary variables and are mutually exclusive – if you are Treated, you cannot also be Control.</p></li>
<li><p>Note that the formula applies to everyone in the population, not just the 115 people for whom we have data. The index <span class="math inline">\(i\)</span> does not just go from 1 through 115. It goes from 1 through <span class="math inline">\(N\)</span>, where <span class="math inline">\(N\)</span> is the number of individuals in the population. Conceptually, everyone has an <code>att_end</code> under treatment and under control.</p></li>
</ul>
<!-- DK: Above is not overly clear. --><ul>
<li><p>The last part, <span class="math inline">\(\epsilon_i\)</span> (“epsilon”), represents the unexplained part and is called the error term. It is simply the difference between the outcome and our model predictions. In our particular case, this includes all factors that have an influence on someone’s attitude toward immigration but are not explained by treatment status. We assume that this error follows a normal distribution with an expected value of 0.</p></li>
<li><p>The small <span class="math inline">\(i\)</span>’s are an index for the data set. It is equivalent to the “ID” column in our Preceptor Table and simply states that the outcome for person <span class="math inline">\(i\)</span> is explained by the predictor variables (<span class="math inline">\(treatment\)</span> and <span class="math inline">\(control\)</span>) for person <span class="math inline">\(i\)</span>, along with an error term.</p></li>
</ul>
</div>
<div id="courage-3" class="section level3" number="8.3.3">
<h3>
<span class="header-section-number">8.3.3</span> Courage<a class="anchor" aria-label="anchor" href="#courage-3"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-599"></span>
<img src="other/images/Courage.jpg" alt="Courage" width="100%"><p class="caption">
FIGURE 8.7: Courage
</p>
</div>
<p>With Justice satisfied, we gather our Courage and fit the model. Note that, except for the change in variable names, the code is exactly the same as it was above, in our predictive model for age. <em>Predictive models and causal models use the same math and the same code.</em> The differences, and they are very important, lie in the interpretation of the results, not in their creation.</p>
<div class="sourceCode" id="cb772"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit_2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">att_end</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">-</span> <span class="fl">1</span>, 
                      data <span class="op">=</span> <span class="va">trains</span>, 
                      seed <span class="op">=</span> <span class="fl">45</span>,
                      refresh <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>

<span class="va">fit_2</span></code></pre></div>
<pre><code>## stan_glm
##  family:       gaussian [identity]
##  formula:      att_end ~ treatment - 1
##  observations: 115
##  predictors:   2
## ------
##                  Median MAD_SD
## treatmentTreated 10.0    0.4  
## treatmentControl  8.5    0.3  
## 
## Auxiliary parameter(s):
##       Median MAD_SD
## sigma 2.8    0.2   
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p><code>treatmentTreated</code> corresponds to <span class="math inline">\(\beta_1\)</span>. As always, R has, behind the scenes, estimated the entire posterior probability distribution for <span class="math inline">\(\beta_1\)</span>. We will graph that distribution in the next section. But the basic print method for these objects can’t show the entire distribution, so it gives us summary numbers: the median and the MAD SD. Speaking roughly, we would expect about 95% of the values in the posterior to be within two MAD SD’s of the median. In other words, we are 95% confident that the true, but unknowable, average attitude toward immigration among the Treated in the population to be between 9.2 and 10.8.</p>
<p><code>treatmentControl</code> corresponds to <span class="math inline">\(\beta_2\)</span>. The same analysis applies. We are about 95% confident that the true value for the average attitude toward immigration for Control in the population is between 7.9 and 9.1.</p>
<p>Up until now, we have used the Bayesian interpretation of “confidence interval.” This is also the intuitive meaning which, outside of academia, is almost universal. There is a truth out there. We don’t know, and sometimes can’t know, the truth. A confidence interval, and its associated confidence level, tells us how likely the truth is to lie within a specific range. If your boss asks you for a confidence interval, she almost certainly is using this interpretation.</p>
<p>But, in contemporary academic research, the phrase “confidence interval” is usually given a “Frequentist” interpretation. (The biggest divide in statistics is between Bayesians and Frequentist interpretations. The Frequentist approach, also known as “Classical” statistics, has been dominant for 100 years. Its power is fading, which is why this textbook uses the Bayesian approach.) For a Frequentist, a 95% confidence interval means that, if we were to apply the procedure we used in an infinite number of future situations like this, we would expect the true value to fall within the calculated confidence intervals 95% of the time. In academia, a distinction is sometimes made between <em>confidence intervals</em> (which use the Frequentist interpretation) and <em>credible intervals</em> (which use the Bayesian interpretation). We won’t worry about that difference in this <em>Primer</em>.</p>
<p>Let’s look at the full posteriors for both <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>.</p>
<!-- DK: Change Parameter levels to something nice. -->
<div class="sourceCode" id="cb774"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit_2</span> <span class="op">%&gt;%</span> 
  <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">sigma</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">pivot_longer</span><span class="op">(</span>cols <span class="op">=</span> <span class="va">treatmentTreated</span><span class="op">:</span><span class="va">treatmentControl</span>,
               names_to <span class="op">=</span> <span class="st">"Parameter"</span>,
               values_to <span class="op">=</span> <span class="st">"attitude"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">attitude</span>, fill <span class="op">=</span> <span class="va">Parameter</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">count</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
                   alpha <span class="op">=</span> <span class="fl">0.5</span>, 
                   bins <span class="op">=</span> <span class="fl">100</span>, 
                   position <span class="op">=</span> <span class="st">"identity"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Posterior for Expected Attitude Toward Immigration"</span>,
         subtitle <span class="op">=</span> <span class="st">"Treated individuals are more conservative"</span>,
         x <span class="op">=</span> <span class="st">"Attitude"</span>,
         y <span class="op">=</span> <span class="st">"Probability"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-601-1.png" width="100%"></div>
<p>It appears that the affect of the treatment is to change people’s attitudes to be more conservative about immigration issues. Which is somewhat surprising!</p>
<p>We can decompose the the dependent variable, <code>att_end</code> into two parts: the fitted values and the residuals. There are only two possible fitted values, one for the Treated and one for the Control. The residuals, as always, are simply the difference between the outcomes and the fitted values.</p>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-602-1.png" width="100%"></div>
<p>The smaller the spread of the residuals, the better a job the model is doing of explaining the outcomes.</p>
<!-- DK: more details! -->
<!-- MM: Add explanation of fit similar to how it was done previously? -->
</div>
<div id="temperance-3" class="section level3" number="8.3.4">
<h3>
<span class="header-section-number">8.3.4</span> Temperance<a class="anchor" aria-label="anchor" href="#temperance-3"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-603"></span>
<img src="other/images/Temperance.jpg" alt="Temperance" width="100%"><p class="caption">
FIGURE 8.8: Temperance
</p>
</div>
<p>Recall the first question with which we began this section:</p>
<ul>
<li>What is the average treatment effect, of exposing people to Spanish-speakers, on their attitudes toward immigration?</li>
</ul>
<!-- DK: Below is also not clear. --><p>Chapter <a href="rubin-causal-model.html#rubin-causal-model">4</a> defined the <em>average treatment effect</em>. One simple estimator of the average treatment effect is the difference between <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>. After all, the definition of <span class="math inline">\(\beta_1\)</span> is the average attitude toward immigration, of the population, for anyone, under exposure to the treatment. So, <span class="math inline">\(\beta_1 - \beta_2\)</span> is the average treatment effect for the population, roughly 1.5. However, estimating the posterior probability distribution for this parameter is tricky, unless we make use of the posterior distributions of <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>. With that information, the problem is simple:</p>
<div class="sourceCode" id="cb775"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit_2</span> <span class="op">%&gt;%</span> 
  <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ate <span class="op">=</span> <span class="va">treatmentTreated</span> <span class="op">-</span> <span class="va">treatmentControl</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">ate</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">count</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
                   bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Posterior for Average Treatment Effect"</span>,
         subtitle <span class="op">=</span> <span class="st">"Exposure to Spanish-speakers shifts immigration attitudes rightward"</span>,
         x <span class="op">=</span> <span class="st">"Difference in Attitude"</span>,
         y <span class="op">=</span> <span class="st">"Probability"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-604-1.png" width="100%"></div>
<p>Could the true value of the average treatment effect be as much as 2 or as little as 1? Of course! The most likely value is around 1.5, but the variation in the data and the smallness of our sample cause the estimate to be imprecise. However, it is quite unlikely that the true average treatment effect is below zero.</p>
<!-- MM: establish that approximate 1.5 difference can be seen by the attitude posterior from courage -->
<p>We can use <code><a href="https://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html">posterior_epred()</a></code> to answer this question. Create a tibble and use it as we have done before:</p>
<div class="sourceCode" id="cb776"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">newobs</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>treatment <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Treated"</span>, <span class="st">"Control"</span><span class="op">)</span><span class="op">)</span>

<span class="va">pe</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html">posterior_epred</a></span><span class="op">(</span><span class="va">fit_2</span>, <span class="va">newobs</span><span class="op">)</span> <span class="op">%&gt;%</span> 
    <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>ate <span class="op">=</span> <span class="va">`1`</span> <span class="op">-</span> <span class="va">`2`</span><span class="op">)</span>

<span class="va">pe</span></code></pre></div>
<pre><code>## # A tibble: 4,000 x 3
##      `1`   `2`   ate
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 10.0   8.56 1.47 
##  2  9.94  8.33 1.61 
##  3 10.0   8.48 1.56 
##  4 10.6   8.28 2.36 
##  5 10.6   8.29 2.32 
##  6  9.26  8.81 0.449
##  7 10.4   8.42 1.96 
##  8 10.5   8.28 2.26 
##  9 10.8   8.51 2.25 
## 10 10.3   8.37 1.88 
## # … with 3,990 more rows</code></pre>
<p>The posterior probability distribution created with <code><a href="https://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html">posterior_epred()</a></code> is the same as the one produced by manipulating the parameters directly.</p>
<div class="sourceCode" id="cb778"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pe</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">ate</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">count</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
                   bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Posterior for Average Treatment Effect"</span>,
         subtitle <span class="op">=</span> <span class="st">"Exposure to Spanish-speakers shifts immigration attitudes rightward"</span>,
         x <span class="op">=</span> <span class="st">"Difference in Attitude"</span>,
         y <span class="op">=</span> <span class="st">"Probability"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-606-1.png" width="100%"></div>
<!-- DK: Much more discussion. Explain what a test might be used for in this situation and why we should reject testing. -->
<p>Our second question:</p>
<ul>
<li>What is the largest effect size which still has a 1 in 10 chance of occurring?</li>
</ul>
<p>Create a tibble which we can pass to <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code>. The variables in the tibble which will be passed in as <code>newdata</code>. Fortunately, the tibble we created above is just what we need for this question also.</p>
<p>Consider the result of <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code> for two people, one treated and one control. Take the difference.</p>
<!-- DK: This goes a bit fast. Slow down. -->
<div class="sourceCode" id="cb779"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict</a></span><span class="op">(</span><span class="va">fit_2</span>, 
                        newdata <span class="op">=</span> <span class="va">newobs</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
    <span class="fu">mutate_all</span><span class="op">(</span><span class="va">as.numeric</span><span class="op">)</span> <span class="op">%&gt;%</span> 
    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>te <span class="op">=</span> <span class="va">`1`</span> <span class="op">-</span> <span class="va">`2`</span><span class="op">)</span>
  
<span class="va">pp</span></code></pre></div>
<pre><code>## # A tibble: 4,000 x 3
##      `1`   `2`      te
##    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
##  1  4.60  6.95 -2.35  
##  2 10.4  10.6  -0.264 
##  3 14.0   7.52  6.53  
##  4 12.2   6.29  5.86  
##  5  8.29  8.34 -0.0451
##  6 10.3   8.00  2.29  
##  7  8.40  5.36  3.04  
##  8 10.0   9.96  0.0732
##  9  6.27  5.93  0.339 
## 10  8.27  2.04  6.22  
## # … with 3,990 more rows</code></pre>
<p>Create a graphic:</p>
<div class="sourceCode" id="cb781"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pp</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">te</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">count</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
                   bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span>  <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Posterior for Treatment Effect for One Person"</span>,
         subtitle <span class="op">=</span> <span class="st">"Causal effects are more variable for indvduals"</span>,
         x <span class="op">=</span> <span class="st">"Difference in Attitude"</span>,
         y <span class="op">=</span> <span class="st">"Probability"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-608-1.png" width="100%"></div>
<p>In this case, we are looking at the distribution of the treatment effect for a single individual. This is very different than the <em>average</em> treatment effect. In particular, it is much more variable. We are looking at one row in the Preceptor Table. For a single individual, <code>att_end</code> can be anywhere from 3 to 15, both under treatment and under control. The causal effect — the difference between the two potential outcomes can, in theory, be anywhere from -12 to +12. Such extreme values are rare, but not impossible.</p>
<p>The question, however, was interested in the value at the 90th percentile.</p>
<div class="sourceCode" id="cb782"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">pp</span><span class="op">$</span><span class="va">te</span>, prob <span class="op">=</span> <span class="fl">0.9</span><span class="op">)</span></code></pre></div>
<pre><code>## 90% 
## 6.9</code></pre>
<p>We would not expect a treatment effect of this magnitude to be common, but, at the same time, effects this big and bigger will occur about 10% of the time.</p>
</div>
</div>
<div id="income-age" class="section level2" number="8.4">
<h2>
<span class="header-section-number">8.4</span> income ~ age<a class="anchor" aria-label="anchor" href="#income-age"><i class="fas fa-link"></i></a>
</h2>
<p>So far, we have only created models in which the predictor variable is discrete, with two possible values. <code>party</code> is either “Democrat” or “Republican.” <code>treatment</code> is either “Treated” or “Control.” Often times, however, the predictor variable will be continuous. Fortunately, the exact same approach works in this case. Consider:</p>
<ul>
<li><em>What would you expect the income to be for a 40-year old?</em></li>
</ul>
<div id="wisdom-5" class="section level3" number="8.4.1">
<h3>
<span class="header-section-number">8.4.1</span> Wisdom<a class="anchor" aria-label="anchor" href="#wisdom-5"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-610"></span>
<img src="other/images/Wisdom.jpg" alt="Wisdom" width="100%"><p class="caption">
FIGURE 8.9: Wisdom
</p>
</div>
<p>Before making a model which seeks to explain <code>income</code>, we should plot it and the variable we think is connected to it.</p>
<!-- MM: Relate to ideal Preceptor tables -->
<div class="sourceCode" id="cb784"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ch8</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">age</span>, y <span class="op">=</span> <span class="va">income</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Income and Age"</span>,
       subtitle <span class="op">=</span> <span class="st">"Older people make more money. Maybe?"</span>,
       x <span class="op">=</span> <span class="st">"Age"</span>,
       y <span class="op">=</span> <span class="st">"Income"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_dollar.html">dollar_format</a></span><span class="op">(</span>accuracy <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-611-1.png" width="100%"></div>
<p>Is that data believable? Maybe? One could imagine that income was not recorded exactly and that, therefore, it is not surprising that many people had exactly the same income. Rounding makes different numbers the same, after all. But what about the (almost) complete lack of people reporting income between $150,000 and $250,000? In a real data science project, this puzzle would require further investigation. For now, we ignore the issue and blithely press on.</p>
<!-- MM: population? -->
</div>
<div id="justice-4" class="section level3" number="8.4.2">
<h3>
<span class="header-section-number">8.4.2</span> Justice<a class="anchor" aria-label="anchor" href="#justice-4"><i class="fas fa-link"></i></a>
</h3>
<!-- MM: Add representativeness and validity -->
<div class="figure">
<span id="fig:unnamed-chunk-612"></span>
<img src="other/images/Justice.jpg" alt="Justice" width="100%"><p class="caption">
FIGURE 8.10: Justice
</p>
</div>
<p>The mathematics for a continuous predictor is unchanged from the intercept-including example we explored in Section <a href="three-parameters.html#addendum">8.2.5</a>:</p>
<p><span class="math display">\[y_i = \beta_0  + \beta_1 age_i + \epsilon_i\]</span></p>
<p>When comparing two people (persons 1 and 2), the first one year older than the second, <span class="math inline">\(\beta_1\)</span> is the expected difference in their incomes. The algebra is simple. Start with the two individuals.</p>
<p><span class="math display">\[y_1 = \beta_0  + \beta_1 age_1\]</span>
<span class="math display">\[y_2 = \beta_0  + \beta_1 age_2\]</span>
We want the difference between them, so we subtract the second from the first, performing that subtraction on both sides of the equals sign.</p>
<p><span class="math display">\[y_1 - y_2 = \beta_0  + \beta_1 age_1 - \beta_0 - \beta_1 age_2\\
y_1 - y_2 = \beta_1 age_1 - \beta_1 age_2\\
y_1 - y_2 = \beta_1 (age_1 - age_2)\]</span></p>
<p>So, if person 1 is one year older than person 2, we have:</p>
<p><span class="math display">\[y_1 - y_2 = \beta_1 (age_1 - age_2)\\
y_1 - y_2 = \beta_1 (1)\\
y_1 - y_2 = \beta_1\]</span></p>
<p>The algebra demonstrates that <span class="math inline">\(\beta_1\)</span> is the same for all ages. The difference in expected income between two people aged 23 and 24 is the same as the difference between two people aged 80 and 81. Is that plausible? Maybe. <em>The algebra does not lie.</em> When we create a model like this, this is the assumption we are making.</p>
<p>Note how careful we are not to imply that increasing age by one year “causes” an increase in income. That is nonsense! <em>No causation without manipulation.</em> Since it is impossible to change someone’s age, there is only one potential outcome. With only one potential outcome, a causal effect is not defined.</p>
</div>
<div id="courage-4" class="section level3" number="8.4.3">
<h3>
<span class="header-section-number">8.4.3</span> Courage<a class="anchor" aria-label="anchor" href="#courage-4"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-613"></span>
<img src="other/images/Courage.jpg" alt="Courage" width="100%"><p class="caption">
FIGURE 8.11: Courage
</p>
</div>
<p>The use of <code><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm()</a></code> is the same as usual.</p>
<div class="sourceCode" id="cb785"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit_3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span><span class="va">income</span> <span class="op">~</span> <span class="va">age</span>, 
                  data <span class="op">=</span> <span class="va">trains</span>, 
                  seed <span class="op">=</span> <span class="fl">28</span>,
                  refresh <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>

<span class="fu"><a href="https://docs.ropensci.org/skimr/reference/print.html">print</a></span><span class="op">(</span><span class="va">fit_3</span>, details <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<pre><code>## stan_glm
##  family:       gaussian [identity]
##  formula:      income ~ age
##  observations: 115
##  predictors:   2
## ------
##             Median   MAD_SD  
## (Intercept) 104783.8  25577.1
## age            877.7    578.5
## 
## Auxiliary parameter(s):
##       Median  MAD_SD 
## sigma 74186.1  4820.3
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p><em>When comparing two individuals, one 30 years old and one 40, we expect the older to earn about $9,000 more. But we are far from certain: the 95% confidence interval ranges from -$3,000 to $20,000.</em></p>
<p>The above is a good summary of the models.</p>
<ul>
<li><p>It is brief! No one wants to listen to too much of your prattle. One sentence gives a number of interest. The second sentence provides a confidence interval.</p></li>
<li><p>It rounds appropriately. No one wants to hear a bunch of decimals. Use sensible units.</p></li>
<li><p>It does not just blindly repeat numbers in the printed display. A one year difference in age, which is associated with a $900 difference in income, is awkward. (We think.) A decade comparison is more sensible.</p></li>
<li><p>“When comparing” is a great phrase to start the summary of any non-causal model. Avoid language like “associated with” or “leads to” or “implies” or anything which even hints at a causal claim.</p></li>
</ul>
<p>Consider our usual decomposition of the outcome into two parts: the model and the error term.</p>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-615-1.png" width="100%"></div>
<p>There are scores of different fitted values. Indeed, there are a greater number of different fitted values than there are different outcome values! This is often true for models which have continuous predictor variables, we have here with <code>age</code>.</p>
<!-- DK: Next step: A scatter plot with the fitted line drawn through it and a residual highlighted. -->
<!-- DK: Some more discussion! And some plots. Explain what the residuals are. And predicted values! Talk about sigma. More could be done. -->
<!-- MM: Agree, some discussion could possibly be one earlier with residuals and predicted values and reinforced throughout -->
</div>
<div id="temperance-4" class="section level3" number="8.4.4">
<h3>
<span class="header-section-number">8.4.4</span> Temperance<a class="anchor" aria-label="anchor" href="#temperance-4"><i class="fas fa-link"></i></a>
</h3>
<div class="figure">
<span id="fig:unnamed-chunk-616"></span>
<img src="other/images/Temperance.jpg" alt="Temperance" width="100%"><p class="caption">
FIGURE 8.12: Temperance
</p>
</div>
<p>Recall our question:</p>
<p><em>What would you expect the income to be for a random 40 year old?</em></p>
<p>Given that we are looking for an expected value, we use <code><a href="https://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html">posterior_epred()</a></code>.</p>
<div class="sourceCode" id="cb787"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">newobs</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>age <span class="op">=</span> <span class="fl">40</span><span class="op">)</span>

<span class="va">pe</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html">posterior_epred</a></span><span class="op">(</span><span class="va">fit_3</span>, newdata <span class="op">=</span> <span class="va">newobs</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> 

<span class="va">pe</span></code></pre></div>
<pre><code>## # A tibble: 4,000 x 1
##        `1`
##      &lt;dbl&gt;
##  1 131988.
##  2 132900.
##  3 143766.
##  4 149269.
##  5 138030.
##  6 135142.
##  7 145487.
##  8 147361.
##  9 131460.
## 10 147589.
## # … with 3,990 more rows</code></pre>
<p>Plotting is the same as always.</p>
<div class="sourceCode" id="cb789"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pe</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">`1`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">count</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
                   bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span>  <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Posterior for Expected Income"</span>,
         subtitle <span class="op">=</span> <span class="st">"A 40-years old commuter earns around $140,000"</span>,
         x <span class="op">=</span> <span class="st">"Income"</span>,
         y <span class="op">=</span> <span class="st">"Probability"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_x_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_dollar.html">dollar_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-618-1.png" width="100%"></div>
<!-- DK: More discussion! -->
</div>
</div>
<div id="liberal-income" class="section level2" number="8.5">
<h2>
<span class="header-section-number">8.5</span> liberal ~ income<a class="anchor" aria-label="anchor" href="#liberal-income"><i class="fas fa-link"></i></a>
</h2>
<p>So far in this chapter, we have only considered <em>continuous</em> outcome variables. <code>age</code>, <code>att_end</code> and <code>income</code> all take on a variety of values. None of them are, truly, continuous, of course. <code>age</code> is only reported as an integer value. <code>att_end</code> can only, by definition, take on 13 distinct values. However, from a modeling perspective, what matters is that they have more than 2 possible values.</p>
<p><code>liberal</code>, however, only takes on two values: TRUE and FALSE. In order to model it, we must use the <code>binomial</code> family. We begin, as always, with some questions:</p>
<p><em>Among all people who have an income $100,000, what proportion are liberal?</em></p>
<p><em>Assume we have a group of eight people, two of whom make $100,000, two $200,000, two $300,000 and two $400,000. How many will be liberal?</em></p>
<div id="wisdom-6" class="section level3" number="8.5.1">
<h3>
<span class="header-section-number">8.5.1</span> Wisdom<a class="anchor" aria-label="anchor" href="#wisdom-6"><i class="fas fa-link"></i></a>
</h3>
<!-- MM: Ideal preceptor table -->
<p>Look at our data.</p>
<div class="sourceCode" id="cb790"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ch8</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">income</span>, y <span class="op">=</span> <span class="va">liberal</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_jitter</span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0</span>, height <span class="op">=</span> <span class="fl">0.1</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Liberal Status by Income in Trains Dataset"</span>,
       subtitle <span class="op">=</span> <span class="st">"Where the gap in the income distribution?"</span>,
       x <span class="op">=</span> <span class="st">"Income"</span>,
       y <span class="op">=</span> <span class="st">"Liberal"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_x_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_dollar.html">dollar_format</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-619-1.png" width="100%"></div>
<p>Why is there only one observation with an income between $135,000 and $250,000? We don’t know. The important thing is to notice it, to explore the variables you are using in the model.</p>
<!-- MM: Is the data of the same population or close enough? Ch.5 states representativeness is in Justice -->
<p>The second part of Wisdom is examining whether the data we have is representative of the overall population about which we seek to draw inferences. Our data is from 2012 and includes only Boston-area commuters. Our questions are, apparently, about today. Are they for the world, the US, the Boston-area, or just commuters at these select train stations? We don’t know! The questions are not very precise.</p>
<p>One of the key jobs of a data scientist is to guide people — our colleagues, bosses and clients — toward asking precise questions. We must help them to translate English into inference. That translation requires precision. In this case, let’s assume that the questions reference Boston-area commuters in 2021.</p>
<p>So, is the data we have from 2012 representative of the data from 2021 about which we seek to draw inferences? Maybe? There is rarely a correct answer to this question. Some things have changed in Boston and some things have not. Our job is to think about these changes and adjust our confidence in our final answers accordingly. Or, in the worst case scenario, if there is no way to understand our actual data and our desired data as coming from the same population, we must stop the project right there.</p>
</div>
<div id="justice-5" class="section level3" number="8.5.2">
<h3>
<span class="header-section-number">8.5.2</span> Justice<a class="anchor" aria-label="anchor" href="#justice-5"><i class="fas fa-link"></i></a>
</h3>
<!-- MM: Add representativeness and validity -->
<p>Recall the discussion in Section <a href="two-parameters.html#zero-one-outcomes">7.5</a> about the logistic regression model which we use whenever the outcome or dependent variable is binary/logical. The math is there, if you care about math. We don’t, at least not too much. Reminder:</p>
<p><span class="math display">\[p(\text{Liberal}_i = \text{TRUE}) = \frac{\text{exp}(\beta_0 + \beta_1 \text{income}_i)}{1 + \text{exp}(\beta_0 + \beta_1 \text{income}_i)}\]</span></p>
<p>This model only has two parameters, <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. But these parameters do not have simple interpretations, unlike the parameters in a linear (or gaussian) model.</p>
<p>Recall the fundamental structure of all data science problems:</p>
<p><span class="math display">\[\text{outcome} = \text{model} + \text{what is not in the model}\]</span>
The exact mathematics of the model — the parameters, their interpretations — are all just <a href="https://en.wikipedia.org/wiki/Dross">dross</a> in the foundry of our inferences: unavoidable but not worth too much of our time.</p>
<p>Even if the math is ignorable, the causal versus predictive nature of the model is not. Is this a causal model or a predictive model? It depends! It could be causal if you assume that we can <em>manipulate</em> someone’s income, if, that is, there are at least two potential outcomes: person <span class="math inline">\(i\)</span>’s liberal status if she makes X dollars and person <span class="math inline">\(i\)</span>’s liberal status if she makes Y dollars. Remember: <em>No causation without manipulation</em>. The definition of a causal effect is the difference between two potential outcomes. If you only have one outcome, then your model can not be causal.</p>
<p>In many circumstances, we don’t really care if a model is causal or not. We might only want to forecast/predict/explain the outcome variable. In that case, whether we can interpret the influence of a variable as causal is irrelevant to our use of that variable.</p>
</div>
<div id="courage-5" class="section level3" number="8.5.3">
<h3>
<span class="header-section-number">8.5.3</span> Courage<a class="anchor" aria-label="anchor" href="#courage-5"><i class="fas fa-link"></i></a>
</h3>
<p>Fitting a logistic model is easy. We use all the same arguments as usual, but with <code>family = binomial</code> added.</p>
<div class="sourceCode" id="cb791"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">fit_4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">ch8</span>,
                  formula <span class="op">=</span> <span class="va">liberal</span> <span class="op">~</span> <span class="va">income</span>,
                  family <span class="op">=</span> <span class="va">binomial</span>,
                  refresh <span class="op">=</span> <span class="fl">0</span>,
                  seed <span class="op">=</span> <span class="fl">365</span><span class="op">)</span></code></pre></div>
<p>Having fit the model, we can look at a printed summary. Note the use of the <code>digits</code> argument to display more digits in the printout.</p>
<div class="sourceCode" id="cb792"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://docs.ropensci.org/skimr/reference/print.html">print</a></span><span class="op">(</span><span class="va">fit_4</span>, digits <span class="op">=</span> <span class="fl">6</span><span class="op">)</span></code></pre></div>
<pre><code>## stan_glm
##  family:       binomial [logit]
##  formula:      liberal ~ income
##  observations: 115
##  predictors:   2
## ------
##             Median   MAD_SD  
## (Intercept)  5.6e-01  4.3e-01
## income      -6.0e-06  3.0e-06
## 
## ------
## * For help interpreting the printed output see ?print.stanreg
## * For info on the priors used see ?prior_summary.stanreg</code></pre>
<p>Fitted models tell us about the posterior distributions for the parameters in the formula which defines the model we have estimated. <em>We are assuming that the model is true.</em> And, as discussed in Chapter <a href="one-parameter.html#one-parameter">6</a>, that assumption is always false! Our model is never a perfectly accurate representation of reality. But, if it were perfect, then the posterior distributions which we have created for <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and so on would be perfect as well.</p>
<p>When working with a linear model, we will often interpret the meaning of the parameters, as we have already done in the first three sections of this chapter. Such interpretations are much harder with logistic models because the math is much less convenient. So, we won’t even bother to try to understand the meaning of these parameters. However, we can note that <span class="math inline">\(\beta_1\)</span> is negative, suggesting that people with higher incomes are less likely to be liberal.</p>
</div>
<div id="temperance-5" class="section level3" number="8.5.4">
<h3>
<span class="header-section-number">8.5.4</span> Temperance<a class="anchor" aria-label="anchor" href="#temperance-5"><i class="fas fa-link"></i></a>
</h3>
<p><em>Among all people who have an income $100,000, what proportion are liberal?</em></p>
<p>Although our model is now logistic, all the steps in answering a question like this are the same as with a linear/guassian model.</p>
<div class="sourceCode" id="cb794"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">newobs</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>income <span class="op">=</span> <span class="fl">100000</span><span class="op">)</span>

<span class="va">pe</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html">posterior_epred</a></span><span class="op">(</span><span class="va">fit_4</span>, 
                      newdata <span class="op">=</span> <span class="va">newobs</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><code>pe</code> is a tibble with a single vector. That vector is 4,000 draws from the posterior distribution of proportion of people, among those who make $100,000, who are liberal. The population proportion is the same thing as the probability for any single individual.</p>
<div class="sourceCode" id="cb795"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pe</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">`1`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">count</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
                   bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span>  <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Posterior for Proportion Liberal Among $100,000 Earners"</span>,
         subtitle <span class="op">=</span> <span class="st">"The population proportion is the same as the probability for any individual"</span>,
         x <span class="op">=</span> <span class="st">"Income"</span>,
         y <span class="op">=</span> <span class="st">"Probability of Being Liberal"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_x_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span>accuracy <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span>accuracy <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-623-1.png" width="100%"></div>
<!-- MM: Mini discussion of graph? -->
<p><em>Assume we have a group of eight people, two of whom make $100,000, two $200,000, two $300,000 and two $400,000. How many will be liberal?</em></p>
<p>Because we are trying to predict the outcome for a small number of units, we use <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code>. The more complex the questions we ask, the more care we need to devote to making the <code>newobs</code> tibble. We use the same <code>rowwise()</code> and <code>c_across()</code> tricks as earlier in the chapter.</p>
<div class="sourceCode" id="cb796"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">newobs</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>income <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">100000</span>, <span class="fl">2</span><span class="op">)</span>,
                            <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">200000</span>, <span class="fl">2</span><span class="op">)</span>,
                            <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">300000</span>, <span class="fl">2</span><span class="op">)</span>,
                            <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">400000</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>
                 

<span class="va">pp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict</a></span><span class="op">(</span><span class="va">fit_4</span>, 
                        newdata <span class="op">=</span> <span class="va">newobs</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">as_tibble</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">mutate_all</span><span class="op">(</span><span class="va">as.numeric</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu">rowwise</span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>total <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu">c_across</span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="va">pp</span></code></pre></div>
<pre><code>## # A tibble: 4,000 x 9
## # Rowwise: 
##      `1`   `2`   `3`   `4`   `5`   `6`   `7`   `8` total
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1     0     0     0     1     1     0     0     0     2
##  2     0     0     0     0     1     0     0     0     1
##  3     1     0     0     0     0     0     0     0     1
##  4     0     0     0     0     0     0     0     1     1
##  5     0     1     0     0     0     1     0     0     2
##  6     0     1     1     0     0     0     0     0     2
##  7     1     0     1     0     0     0     0     1     3
##  8     0     0     0     0     1     0     1     0     2
##  9     1     1     0     0     0     0     0     0     2
## 10     0     1     0     1     1     0     0     1     4
## # … with 3,990 more rows</code></pre>
<p>Study the <code>pp</code> tibble. Understand its component parts. The first column, for example, is 4,000 draws from the posterior distribution for the liberal status of a random person with an income of $100,000. Note how all the draws are zeroes or ones. That is very different from the draws we have seen before! But it also makes sense. We are making a prediction about a binary variable, a variable which only have two possible values: zero or one. So, any (reasonable!) predictions will only be zero or one.</p>
<p>The second column is the same thing as the first column. Both are 4,000 draws from the posterior distribution for the liberal status of a random person with an income of $100,000. Yet they also have different values. They are both the same thing and different things, in the same way that <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm(10)</a></code> and <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm(10)</a></code> are the same thing — both are 10 draws from the standard normal distribution — and different things in that the values vary.</p>
<p>The third and fourth columns are different from the first two columns. They are both 4,000 draws from the posterior distribution for the liberal status of a random person with an income of $200,000. And so on for later columns. We can answer very difficult questions by putting together simple building blocks, each of them a set of draws from a posterior distribution. Recall the discussion in Section <a href="wrangling.html#distributions">2.8</a>.</p>
<p>The <code>total</code> column is simply the sum of the first eight columns. Having created the building blocks with 8 columns of draws from four different posterior distributions, we can switch our focus to each row. Consider row 2. It has a vector of 8 numbers: <code>1 1 1 0 0 1 0 0</code>. We can treat that vector as a unit of analysis. This is what might happen with our 8 people. The first three might be liberal, the fourth not liberal and so on. This row is just one example of what might happen, one draw from the posterior distribution of possible outcomes for groups of eight people with these incomes.</p>
<p>We can simplify this draw by taking the sum, or doing anything else which might answer the question with which we are confronted. Posterior distributions are as flexible as individual numbers. We can, more or less, just use algebra to work with them.</p>
<p>Graphically we have:</p>
<div class="sourceCode" id="cb798"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">pp</span> <span class="op">%&gt;%</span> 
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">total</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">geom_histogram</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y <span class="op">=</span> <span class="fu">after_stat</span><span class="op">(</span><span class="va">count</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">count</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,
                   bins <span class="op">=</span> <span class="fl">100</span><span class="op">)</span>  <span class="op">+</span>
    <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Posterior for Number of Liberals in Group with Varied Incomes"</span>,
         subtitle <span class="op">=</span> <span class="st">"Two is the most likely number, but values from 0 to 5 are plausible"</span>,
         x <span class="op">=</span> <span class="st">"Number of Liberals"</span>,
         y <span class="op">=</span> <span class="st">"Probability"</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_x_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_number.html">number_format</a></span><span class="op">(</span>accuracy <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">scale_y_continuous</span><span class="op">(</span>labels <span class="op">=</span> <span class="fu">scales</span><span class="fu">::</span><span class="fu"><a href="https://scales.r-lib.org/reference/label_percent.html">percent_format</a></span><span class="op">(</span>accuracy <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
    <span class="fu">theme_classic</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="book_temp_files/figure-html/unnamed-chunk-625-1.png" width="100%"></div>
<p>As always, there is some <em>truth</em>. If, tomorrow, we were to meet 8 new people, with the specified incomes, a certain number of them would be liberal. If we had the ideal Preceptor Table, we could just look up that number. No data science required. Alas, we don’t know the truth. The bets we can do is to create a posterior distribution for that unknown value, as we have done here. We then need to translate that posterior into English — “The most likely number of liberals is 2 or 3, but a total as low as zero or as high as 5 is also plausible. Having 6 liberals would be really surprising. Having 7 or 8 is almost impossible.”</p>
<p>Are these two posterior probability distributions perfect? No! This is the central message of the virtue of Temperance. We must demonstrate our humility when we use our models. Recall the distinction between the <em>unknown true distribution</em> and the <em>estimated distribution</em>. The first is the posterior distribution we would create of we understood every detail of the process and could accurately model it. We would still not know the true unknown number, but our posterior distribution for that number would be perfect. Yet, our model is never perfect. We are making all sorts of assumptions behind the scenes. Some of those assumptions are plausible. Others are less so. Either way, the <em>estimated distribution</em> is what we have graphed above.</p>
<p>The central lesson of Temperance is: Don’t confuse the <em>estimated</em> posterior (which is what you have) with the <em>true</em> posterior (which is what you want). Recognize the unavoidable imperfections in the process. You can still use your estimated posterior — what choice do you have? — but be cautious and humble in doing so. The more that you suspect that your estimated posterior differs from the true posterior, the more humble and cautious you should be.</p>
</div>
</div>
<div id="summary-8" class="section level2" number="8.6">
<h2>
<span class="header-section-number">8.6</span> Summary<a class="anchor" aria-label="anchor" href="#summary-8"><i class="fas fa-link"></i></a>
</h2>
<p>In this chapter, we explored relationships between different variables in the <code>trains</code> data set. We built three predictive models and one causal model.</p>
<p>Similar to previous chapters, our first task is to use <em>Wisdom</em> . We judge how relevant our data is to the questions we ask. Is it reasonable to consider the data we have (e.g., income and age data from Boston commuters in 2012) as being drawn from the same population as the data we want to have (e.g., income and age data from today for the entire US)? Probably?</p>
<p><em>Justice</em> is necessary to decide the best way to represent the models we make. A little math won’t kill you. We use <em>Courage</em> to translate our models into code. Our goal is to understand, generate posterior distributions for the parameters, and interpret their meaning. <em>Temperance</em> leads us to the final stage, using our models to answer our questions.</p>
<p><em>Key commands:</em></p>
<ul>
<li><p>Create a model with <code><a href="https://mc-stan.org/rstanarm/reference/stan_glm.html">stan_glm()</a></code>.</p></li>
<li><p>Use <code><a href="https://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html">posterior_epred()</a></code> to estimate expected values. The <strong>e</strong> in <strong>e</strong>pred stands for <strong>e</strong>xpected.</p></li>
<li><p>Use <code><a href="https://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html">posterior_predict()</a></code> to make forecasts for individuals. The variable in predictions is always greater than the variability in expectations because predictions can’t pretend that <span class="math inline">\(\epsilon_i\)</span> is zero.</p></li>
</ul>
<p>Once we have draws from a posterior distribution for our outcome variable — whether that be an expectation or a prediction — we can manipulate those draws to answer our question.</p>
<p><em>Remember:</em></p>
<ul>
<li><p><em>Always explore your data.</em></p></li>
<li><p><em>Predictive models care little about causality.</em></p></li>
<li><p><em>Predictive models and causal models use the same math and the same code.</em></p></li>
<li><p><em>“When comparing” is a great phrase to start the summary of any non-causal model.</em></p></li>
<li><p><em>Don’t confuse the estimated posterior (which is what you have) with the true posterior (which is what you want). Be humble and cautious in your use of the posterior.</em></p></li>
</ul>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="two-parameters.html"><span class="header-section-number">7</span> Two Parameters</a></div>
<div class="next"><a href="four-parameters.html"><span class="header-section-number">9</span> Four Parameters</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#three-parameters"><span class="header-section-number">8</span> Three Parameters</a></li>
<li>
<a class="nav-link" href="#wisdom-2"><span class="header-section-number">8.1</span> Wisdom</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#the-questions"><span class="header-section-number">8.1.1</span> The Questions</a></li>
<li><a class="nav-link" href="#eda-for-trains"><span class="header-section-number">8.1.2</span> EDA for trains</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#age-party"><span class="header-section-number">8.2</span> age ~ party</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#wisdom-3"><span class="header-section-number">8.2.1</span> Wisdom</a></li>
<li><a class="nav-link" href="#justice-2"><span class="header-section-number">8.2.2</span> Justice</a></li>
<li><a class="nav-link" href="#courage-2"><span class="header-section-number">8.2.3</span> Courage</a></li>
<li><a class="nav-link" href="#temperance-2"><span class="header-section-number">8.2.4</span> Temperance</a></li>
<li><a class="nav-link" href="#addendum"><span class="header-section-number">8.2.5</span> Addendum</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#att_end-treatment"><span class="header-section-number">8.3</span> att_end ~ treatment</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#wisdom-4"><span class="header-section-number">8.3.1</span> Wisdom</a></li>
<li><a class="nav-link" href="#justice-3"><span class="header-section-number">8.3.2</span> Justice</a></li>
<li><a class="nav-link" href="#courage-3"><span class="header-section-number">8.3.3</span> Courage</a></li>
<li><a class="nav-link" href="#temperance-3"><span class="header-section-number">8.3.4</span> Temperance</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#income-age"><span class="header-section-number">8.4</span> income ~ age</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#wisdom-5"><span class="header-section-number">8.4.1</span> Wisdom</a></li>
<li><a class="nav-link" href="#justice-4"><span class="header-section-number">8.4.2</span> Justice</a></li>
<li><a class="nav-link" href="#courage-4"><span class="header-section-number">8.4.3</span> Courage</a></li>
<li><a class="nav-link" href="#temperance-4"><span class="header-section-number">8.4.4</span> Temperance</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#liberal-income"><span class="header-section-number">8.5</span> liberal ~ income</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#wisdom-6"><span class="header-section-number">8.5.1</span> Wisdom</a></li>
<li><a class="nav-link" href="#justice-5"><span class="header-section-number">8.5.2</span> Justice</a></li>
<li><a class="nav-link" href="#courage-5"><span class="header-section-number">8.5.3</span> Courage</a></li>
<li><a class="nav-link" href="#temperance-5"><span class="header-section-number">8.5.4</span> Temperance</a></li>
</ul>
</li>
<li><a class="nav-link" href="#summary-8"><span class="header-section-number">8.6</span> Summary</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/PPBDS/primer/blob/master/08-three-parameters.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/PPBDS/primer/edit/master/08-three-parameters.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Preceptor’s Primer for Bayesian Data Science</strong>" was written by David Kane. </p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>
</html>
